### ISSUE TITLE
Phar build fails due to unusable GPG key

### ISSUE THREAD

**Issue by bart-jaskulski** [phpbench/phpbench#1016]
Latest releases (1.2.6 and 1.2.7) failed to compile phar files due to GPG key issue.

Take a look at https://github.com/phpbench/phpbench/actions/runs/3255263999/jobs/5344398378#step:5:121

**Comment by dantleech** [comment]
hm, looks like the key expired. unfortunately I can't find the private key at the moment, if it's anywhere. So I'll probably need to create new one :/
