### ISSUE TITLE
Getting a "segmentation fault" error when Xdebug is enabled

### ISSUE THREAD

**Issue by cangokdayi** [phpbench/phpbench#1019]
I'm getting this strange error when Xdebug is enabled or triggered.

```bash
> php ./vendor/bin/phpbench run --report=compact
PHPBench (1.2.8) running benchmarks... #standwithukraine
with configuration file: /var/www/backend/phpbench.json
with PHP version 8.1.10, xdebug ✔, opcache ❌

Segmentation fault
Script php ./vendor/bin/phpbench run --report=compact handling the benchmark event returned with error code 139
```

This is the output of `uname -a` from inside the Docker container
```
Linux 467b5cbf8b65 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dantleech** [comment]
can you:

- add `"runner.remote_script_remove": false` to the config file
- run with `-vvv`

you should then see the commands that are being spawed:

```
[DEBUG] Spawning process: '/usr/bin/php8.1' -dmemory_limit=1G -dxdebug.mode=none -dmax_execution_time=0 '/tmp/daniel/PhpBenchgrdGZC'
```

you could then execute `'/usr/bin/php8.1' -dmemory_limit=1G -dxdebug.mode=none -dmax_execution_time=0 '/tmp/daniel/PhpBenchgrdGZC` in your shell and I (if) it will segfault, but you'll have a better chance of debugging it.

**Comment by cangokdayi** [comment]
> can you:
> 
> * add `"runner.remote_script_remove": false` to the config file
> * run with `-vvv`
> 
> you should then see the processes that are being spawed:
> 
> ```
> [DEBUG] Spawning process: '/usr/bin/php8.1' -dmemory_limit=1G -dxdebug.mode=none -dmax_execution_time=0 '/tmp/daniel/PhpBenchgrdGZC'
> ```
> 
> you could then execute `'/usr/bin/php8.1' -dmemory_limit=1G -dxdebug.mode=none -dmax_execution_time=0 '/tmp/daniel/PhpBenchgrdGZC` in your shell and I (if) it will segfault, but you'll have a better chance of debugging it.

Thanks man, I did find some useful logs and it seems like an issue with php-cli versions but couldn't get a chance to dig into it yet, I'll update this post once I fix it.

**Comment by cangokdayi** [comment]
It seems like there was a mix up with my PHP CLI binaries within the container, I've recreated the container and the binaries from scratch and it works fine now. Sorry for the noise.
