### ISSUE TITLE
doc: Make use of the attributes instead of phpdoc annotations

### ISSUE THREAD

**Issue by theofidry** [phpbench/phpbench#1043]
I was surprised to see the PHPDoc annotations in the docs but you did add attributes quite a while back so I assume the docs just need to be updated too.

**Comment by dantleech** [comment]
the docs have both: https://phpbench.readthedocs.io/en/latest/annotributes.html but right now 7.4 is still supported, I'm going to drop 7.4 and 8.0 in the next release, so maybe then a good time to migrate to attributes being the primary reference in the docs.

**Comment by theofidry** [comment]
Was about to edit the issue as I've just seen that and wonder how I could have missed it. I would suggest to make the attributes the default rather than annotations but actually bumping the whole thing sounds like a better idea :P
