### ISSUE TITLE
Overview report is difficult to understand when ansi mode is off

### ISSUE THREAD

**Issue by llaville** [phpbench/phpbench#1060]
Hello,

First, I would like to say that I'm very happy to run `phpbench` for the first time in a concrete real project.

So as I'm still a newbie with this great tool, perharps I don't yet noticed some cool tips !

I've played with all options, and found perharps a little improvement you may add to the `overview` report (best one on my opinion to begin).

When you run `phpbench` with the `--no-ansi` option, or if the console did not support colors, it's a bit difficult to read graph.
Here is for example, a chunk of one of my run.

![no-ansi](https://github.com/phpbench/phpbench/assets/364342/c4656f5b-c6b8-4737-8ee3-af78900c8be0)

Command executed was : `phpbench run tests/Benchmark/ --report=overview --report=aggregate --ref=php81 --tag=php83 --no-ansi`

Goal is to compare results on PHP 8.1 and 8.3 platform
 
Of course, by default I've colors so it's not really important, but I would just share my feedback !

**Comment by dantleech** [comment]
thanks for the feedback, i'm not sure there's a good way to make that clearer though. this is really an "extra" and if you don't have colors in the terminal then the numbers should speak for themselves :slightly_smiling_face:
