### ISSUE TITLE
Report generate command

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#1096]
Introduce a `config:report:customise` command ot similar to inject an existing report into the `phpbench.json` config, or at least dump an existing report as JSON.

```
config:report:dump expression
```

should then give something that can be copy/pasted into the config file.

**Comment by MrSuddenJoy** [comment]
Why would you need report in `json` file and in `config`?

**Comment by dantleech** [comment]
acutally this is already implemented. the way to define custom reports is in the config file.

```
phpbench config:extend genereator aggregate my_table
```
will generate a report generator called `my_table` based on `aggregate`
