### ISSUE TITLE
Attributes with unrecognized annotations will fail

### ISSUE THREAD

**Issue by boesing** [phpbench/phpbench#1097]
Hey there,

I have a generic benchmark class so that I can test multiple implementations of the same interface at once.
This looks somehow like:

```php
/**
 * @template TOptions of AdapterOptions
 */
#[BeforeMethods('setUp')]
#[AfterMethods('tearDown')]
abstract class AbstractStorageAdapterBenchmark
{}
```

That class is then extended by the concrete implementation benchmark:

```php
/**
 * @template-extends AbstractStorageAdapterBenchmark<RedisClusterOptions>
 */
#[Revs(100)]
#[Iterations(10)]
#[Warmup(1)]
class RedisClusterStorageAdapterBench extends AbstractStorageAdapterBenchmark
{}
```

It seems that phpbench does ignore all attributes once a phpdoc on class level is provided.
I assume that this is a bug?

Ref: https://github.com/laminas/laminas-cache-storage-adapter-redis/actions/runs/9620252082/job/26538088931?pr=101
Ref: https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/573ba3b9e1b1f18152230e5216a9c462a22fc57b/benchmark/RedisClusterStorageAdapterBench.php

```
Running ./vendor/bin/phpbench run --revs=2 --iterations=2 --report=aggregate
No entry for terminal type "unknown";
using dumb terminal settings.
PHPBench (1.2.15) running benchmarks... #standwithukraine
with configuration file: /github/workspace/phpbench.json
with PHP version 8.1.27, xdebug ❌, opcache ❌

Warning:  Could not load metadata for file "/github/workspace/benchmark/RedisClusterStorageAdapterBench.php" - is this file intended to be a benchmark? Perhaps setting the `runner.file_pattern` to `*Bench.php` will help: Unrecognized annotation @template, valid PHPBench annotations: @BeforeMethods, @BeforeClassMethods, @AfterMethods, @AfterClassMethods, @ParamProviders, @Groups, @Iterations, @Revs, @Skip, @Sleep, @OutputTimeUnit, @OutputMode, @Warmup, @Subject, @Assert, @Executor, @Timeout, @Format, @RetryThreshold
```

**Comment by dantleech** [comment]
yes it is a bug. as a workaround you can disable annotations: https://phpbench.readthedocs.io/en/latest/configuration.html#runner-annotations

**Comment by boesing** [comment]
Oh nice, thanks! Was not aware this is possible. That might work, will try later!
