### ISSUE TITLE
PHP 8.4 deprecation of implicit nullable

### ISSUE THREAD

**Issue by codemasher** [phpbench/phpbench#1104]
Hey, just a heads-up that PHP 8.4 is coming soon and PhpBench is yelling a lot because of this: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

tl;dr: all function- and method parameters as well as return types that are nullable need a type declaration for that.
```php
function foo(string $bar = null){}

// should be either (PHP 7.4 compatible, may or may not be deprecated in future)
function foo(?string $bar = null):?string{}

// or PHP8+ union type
function foo(string|null $bar = null):string|null{}
```

Cheers!

**Comment by dantleech** [comment]
See https://github.com/phpbench/phpbench/pull/1109/files

**Comment by dantleech** [comment]
merged into master
