### ISSUE TITLE
Generate XDebug profiles

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#115]
Because iterations are executed in a separate process in near isolation, it should be possible to generate an XDebug profile for any subject. This could be achieved either via. an option or as a separate command.

````
$ phpbench profile /path/to/FooBench.php --subject=benchFoo
````

It will then generate a profile named `<benchmark>-<subject>-<iteration #>-<date><time>.profile`

**Comment by sandrokeil** [comment]
@dantleech What's the purpose for this? Profiler have an overhead and with PHP7 it could lead to try to improve wrong functions.

**Comment by dantleech** [comment]
The idea would be to allow people to profile specific benchmarks, it would be additional functionality.

Basically you would be able to generate for example an XDebug, XHProf or Blackfire profile for any given benchmark subject.

Internally PHPBench uses an instance of `ExecutorInterface` to run the benchmark and retrieve the result (time and memory). Currently there is only `MicrotimeExecutor`. This feature would introduce additionally `XDebugExecutor`, `BlackfireExecutor`, etc, which would be used by the `profile` command, but could additionally be used by the standard `run` command for the sake of comparison (you could measure the overhead perhaps).

Currently its just an interesting idea that I am going to look into.

**Comment by sandrokeil** [comment]
Yes, that idea is really interesting, but I think the benchmark functions are to small to have a benefit of this.

**Comment by dantleech** [comment]
Well, if I understand you, benchmark functions (what we are calling "subjects") could be PHP internal functions, algorithms, or services from a DI container. So if profiling a request is interesting, then so should profiling a "service" (e.g. executing a DQL query in Doctrine ORM, or running a search query with Zend Search).

**Comment by dantleech** [comment]
Done in #254
