### ISSUE TITLE
InvalidArgumentException when benchmark contains usage of ::class

### ISSUE THREAD

**Issue by stagebloc-iceman** [phpbench/phpbench#174]
The Reflector fails to find the name of the benchmark class when the source contains any usage of `::class`. This is due to `class` using the same T_CLASS token number as `class Name { }` so the parser gets confused.

One option is to check for the T_DOUBLE_COLON before searching for the class name, though this may need to be smarter to avoid whitespace (`stdClass :: class` is technically valid).

In Remote/Reflector.php around line 142, change to:
```php
                if ($tokens[$i][0] === T_CLASS && $tokens[$i-1][0] !== T_DOUBLE_COLON) {
```

**Comment by dantleech** [comment]
I can't reproduce this with a class such as follows:

````php
class Foo
{
     public function foobar()
     {
         Foo::class;
     }
}
`````

Nor would I expect it to fail because only the first `class` keyword (should) be used.

Could you show me the benchmark class which this is failing with or add a failing test?

**Comment by stagebloc-iceman** [comment]
Sure, below is the command and bench class I'm using.

```
./vendor/bin/phpbench run Benchmark/ReflectSubclassBench.php 
PhpBench 0.5. Running benchmarks.
Using configuration file: /home/localhost/misc/phpbench.json

PHP Notice:  Uninitialized string offset: 1 in /home/localhost/misc/vendor/phpbench/phpbench/lib/Benchmark/Remote/Reflector.php on line 146

  [InvalidArgumentException]                                                              
  Could not find class in file "/home/localhost/misc/Benchmark/ReflectSubclassBench.php"  

cat phpbench.json 
{
    "bootstrap": "vendor/autoload.php"
}

php -v
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

```php
<?php

namespace Benchmark;

/**
 * @revs(10000)
 * @iterations(5)
 */
class ReflectSubclassBench
{
    protected $class = \Test\B::class;

    public function benchIsSubclassOf()
    {
        is_subclass_of($this->class, \Test\A::class);
    }

    public function benchReflectionClass()
    {
        $c = new \ReflectionClass($this->class);
        $c->isSubclassOf(\Test\A::class);
    }
}
```

I can try pulling down the repo and writing a failing test this evening if still necessary.

**Comment by dantleech** [comment]
Before doing that you might want to try upgrading to the latest tagged version `0.5` (or `master`). Previous versions had a bug whereby the string buffer was truncated too early (resulting in incomplete tokens when detecting the classname) - that might be related - your class looks almost identical to the one I tested on `dev-master`.

**Comment by dantleech** [comment]
ping

**Comment by dantleech** [comment]
ok nevermind, I can reproduce using the class you have given.

**Comment by dantleech** [comment]
Created PR #180

**Comment by dantleech** [comment]
Fixed
