### ISSUE TITLE
Truncate long values in reports

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#184]
Currently cells in report tables can contain very long strings which make reading the table difficult.

For example: http://i.snag.gy/UNsRd.jpg

Truncating the string would fix this issue, but we run the risk of hiding information.

Options:

- Add a "truncate" option to the Tabular report generator which trucates strings, default to true.
- Automatically truncate based on the width of the table (with the console renderer).
- Place each key on a seperate line: will need to see if the Symfony Table class supports this.

**Comment by dantleech** [comment]
I have added both `truncate` and `json_format` functions to Tabular. JSONFormat pretty prints the parameters, which reduces line length, but neither truncate nor json_format can eliminate this problem.

Ultimately this is an issue with the `Table` Symfony class - we cannot currently set the width of the columns (e.g. make the table full size and give a percentage widget to each of the columns).

The solution here I think would be to have a new console table rendering library.

**Comment by dantleech** [comment]
Have added the `pretty_params` option anyway, which improces the situation somewhat: https://github.com/phpbench/phpbench/pull/192

/cc @redaxmedia

**Comment by dantleech** [comment]
A better solution might be to only show a reference to the parameter set e.g. `#1`, `#2` and then show labels below or above the report. This would addiionally make sense in other use cases, for example when drawing graphs.

**Comment by redaxmedia** [comment]
I'm fine with the current solution. This issue can be marked as resolved then...
