### ISSUE TITLE
Provide one argument per parameter, or a single array

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#190]
Currently a single array is provided to benchmarking methods with a `@ParamProvider`:

````php
/**
 * @ParamProviders({"provideFoo"})
 */
public function benchFoo(array $params) 
{
    $x = $param['foo'];
    $y = $param['bar'];
}
````

We could expand the array keys to arguments as with PHPUnit:

````php
/**
 * @ParamProviders({"provideFoo"})
 */
public function benchFoo($foo, $bar) 
{
}
````

Disadvantages:

- Slightly increased call time.
- Multiple parameter providers give a cartesian product, it would be difficult to anticipate the argument order (although we could enforce matching keys to argument names).

**Comment by dantleech** [comment]
The overhead is as follows:

benchmark | subject | group | params | revs | its | rej | time | memory | deviation | stability
 --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- 
CostOfCalling | benchCallWithoutParams | cost_of_calling,group_two | [] | 100000 | 10 | 1 | 1.4537μs | 576b | 0.00% | 91.87%
CostOfCalling | benchCallWithParams | cost_of_calling,group_two | [] | 100000 | 10 | 1 | 1.7462μs | 576b | 20.12% | 91.75%
CostOfCalling | benchUserFuncWithoutParams | cost_of_calling,group_two | [] | 100000 | 10 | 2 | 5.0459μs | 576b | 247.11% | 95.09%
CostOfCalling | benchUserFuncParams | cost_of_calling,group_two | [] | 100000 | 10 | 0 | 5.1732μs | 576b | 255.86% | 92.53%
CostOfCalling | benchReflectionCall | cost_of_calling,group_two | [] | 100000 | 10 | 0 | 2.0964μs | 592b | 44.21% | 93.11%
CostOfCalling | benchReflectionCallWithParams | cost_of_calling,group_two | [] | 100000 | 10 | 1 | 2.7659μs | 592b | 90.26% | 94.46%

**Comment by redaxmedia** [comment]
I really hope you ignore the overhead and stick to the usability / simplicity for the end-user.

**Comment by dantleech** [comment]
I have given this alot of thought over the last week, and have created: https://github.com/phpbench/phpbench/pull/194

However, the approach contains a fatal flaw with regards to providing parameters to `before` and `after` methods, see PR for more info.

**Comment by redaxmedia** [comment]
I can test the master soon, at the moment I'm quite busy...

**Comment by dantleech** [comment]
I have decided finally not to implement this feature: basically the biggest single issue is the fact that we pass the parameters also to the before/after methods - and there is no 1-1 coupling between before/after methods and the `bench` method, so multiple `bench` methods can reuse the same `before` methods.
