### ISSUE TITLE
[RuntimeException] Could not launch script:

### ISSUE THREAD

**Issue by Kanti** [phpbench/phpbench#208]
I get this Exception then i try to run phpbench on windows.
````bash
[RuntimeException]
  Could not launch script:
````
the command I am executing
````
vendor\bin\phpbench.bat run benchmarks/StringifyBench.php
````

Windows 10 1511
php 5.5.8

please help me, I would love to use phpbench :)

**Comment by dantleech** [comment]
hi, it would be great if you could post the benchmark you are trying to run as a [gist](https://gist.github.com), I will then see if I can reproduce the issue.

**Comment by Kanti** [comment]
````php
<?php
namespace Kanti\Bench;

class StringifyBench
{
    public function benchConsume()
    {
        echo "test";
    }
}
````

**Comment by dantleech** [comment]
I get the following error:

````
  [RuntimeException]                                                                                                                                                     │
  Could not decode return value from script from template "/home/daniel/www/phpbench/phpbench/lib/Benchmark/Executor/template/microtime.template" (should be a JSON en   │
  coded string): test{"memory":592,"time":19}
````

The problem is that the benchmark executor returns a JSON string as its STDOUT. Here you are calling `echo` and prepending `test` to that string, which cannot then be decoded.

This is a bug however, we should hide any output caused by the Benchmarking class, I created #209

It is also very strange that you did not get any error output.

Can you confirm that you did not receieve the above error message and tell me which version of PHPBench you are using?

**Comment by Kanti** [comment]
if my bench is as follow, the Exception is still the same.
````php
<?php
namespace Kanti\Bench;

class StringifyBench
{
    public function benchConsume()
    {
        trim('');
    }
}
````

**Comment by dantleech** [comment]
Hmm, that one does work on my (Linux) machine. I would have to install a Windows VM to investigate this further, could you maybe try debugging to see if you can coax a better exception message out? For example have a look in `lib/Benchmark/Remote/Payload.php` to see where that exception message is thrown..

**Comment by Kanti** [comment]
I have tried it, but I couldn't find anything that would help me to get the error.

**Comment by dantleech** [comment]
ok, I will investigate.

**Comment by dantleech** [comment]
Cannot seem to reproduce in Windows 10 with PHP 5.5.12.

**Comment by dantleech** [comment]
Could this somehow be a permissions issue?

**Comment by Kanti** [comment]
With the v0.7.0-dev ``96d8371``

it work's now.

**Comment by dantleech** [comment]
Good news! I wonder what the problem was..
