### ISSUE TITLE
Ability to benchmark PHPUnit test classes - @Benchmark annotation

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#210]
It would be good value if you could benchmark PHPUnit test classes. This should basically be possible, but would require either importing the annotation classes (i.e. depending on PHPBench in the user library) or ignoring the PHPUnit annotations.

**Comment by dantleech** [comment]
f.e.

```php
<?php

class FooTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @PHPBench\SetUp()
     */
    public function setUp()
    {
    }

    public function testFoobar()
    {
        $results = $this->doFoobar();
        $this->assertEquals($a, $b);
        $this->assertEquals($b, $a);
    }

    /**
     * @PHPBench\Benchmark()
     * @PHPBench\Revolutions(100000)
     * @PHPBench\Iterations(100)
     */
    public function doFoobar()
    {
    }
}
```

**Comment by dantleech** [comment]
Fixed in  #411

**Comment by flobee** [comment]
Cool feature! :) I just see this project exists.
Suggestion: A history to compare performance on changes would be good. On the other hand phpunit's file suffix "Test.php" and "Bench.php" i would suggest to split stuff in that way. Anyway. I like your tool and will check it out :)
Kind regards Florian

**Comment by dantleech** [comment]
You can record changes using the `--store` options. For visualizing changes over time there is reports.phpbench.org (https://github.com/phpbench/phpbench-reports) but it is stillin early stages.

**Comment by flobee** [comment]
Cooool :)
