### ISSUE TITLE
Rename iterations to samples

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#222]
"samples" would be a less confusing term than "iterations" I think. `@Samples(10)`.

**Comment by fabpot** [comment]
We are doing the opposite change in Blackfire, from samples to iterations. Samples has a statistical connotation which proved to be confusing to our users.

**Comment by dantleech** [comment]
Yeah, I found out that [JMH](http://openjdk.java.net/projects/code-tools/jmh) also uses that term. Will keep leave it as it is and close this issue I think.
