### ISSUE TITLE
Cannot use with Symfony 3 projects.

### ISSUE THREAD

**Issue by henrikbjorn** [phpbench/phpbench#242]
The composer.json does not allow symfony 3 components to be installed alongside.

**Comment by dantleech** [comment]
Indeed, I will have a look into that. In the meantime it is not necessary to include PHPBench as a dependency to your project, you could install it [globally](http://phpbench.readthedocs.org/en/latest/installing.html#composer-global-install) or symlink it in your path.

**Comment by dantleech** [comment]
See https://github.com/phpbench/phpbench/pull/244

**Comment by dantleech** [comment]
Fixed
