### ISSUE TITLE
Add test for non-standard temp directory with blank space.

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#296]

**Comment by Remo** [comment]
@dantleech Had a quick look, not sure how to test this. We can either try to change the TEMP environment variable, but that feels ugly or we'd have to mock this line: https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Remote/Payload.php#L104

Is there anything in place I've missed?

**Comment by dantleech** [comment]
We could just set the temp dir: `ini_set('sys_temp_dir`, __DIR__ . '/' . $directoryName)` in the test.

We should then create and remove the directory, e.g. `Directory Name With Spaces` before and after the test and also restore the `sys_dir` (or run the test in isolation @ProcssIsolation iirc).

**Comment by dantleech** [comment]
Hm is this working now @Remo ?
