### ISSUE TITLE
Provide a way to reset state/caches at every loop

### ISSUE THREAD

**Issue by Ocramius** [phpbench/phpbench#304]
As of today's [twitter thread](https://twitter.com/Ocramius/status/691293008428429313) and related [example](https://gist.github.com/Ocramius/c495f7104ab5881072ac), it is currently not supported to run benchmarks and reset state at each execution of the benchmark methods.

Basically:

``` php
class MyBench
{
    public function __construct()
    {
        $this->foo = new Foo();
    }
    public function benchFoo()
    {
        $this->foo->reset(); // <- should not be included in benchmark measurement
        $this->foo->doFoo();
    }
}
```

A workaround (for now), is to ensure immutability by de-referencing the system under bench:

``` php
class MyBench
{
    public function __construct()
    {
        $this->foo = new Foo();
    }
    public function benchFoo()
    {
        $foo = clone $this->foo; // <- still some overhead

        $foo->doFoo();
    }
}
```

This needs some research, but it may be possible to have a separate `resetInstance` method (or such) on the benchmark, that can be measured and excluded from the output measurements.

**Comment by dantleech** [comment]
Should we [deep copy](https://packagist.org/packages/myclabs/deep-copy) objects or is `clone `good enough?

**Comment by Ocramius** [comment]
@dantleech deep copy is a responsibility of the object itself, no?

Deep copying would be inefficient, IMO

**Comment by dantleech** [comment]
How about:

```php
public function preRevClone()
{
    $this->fresh = clone $this->sm;
}

/**
 * @preRevMethods({"counterweightClone"})
 */
public function benchFetchFactory1()
{
    $this->fresh->get('invokable1');
}
```

Where all "pre-rev" methods will be benchmarked separtely (by default with the same settings as the subject method) and then deducted from the subjects time-mesurement.

I am not fan of the annotation semantic, but thats the current scheme.

**Comment by Ocramius** [comment]
@dantleech could be done if it is outside the measurement stuff. Not a fan of the annotation approach either, but it worked fine with PHPUnit's `@dataProvider`

**Comment by dantleech** [comment]
So the overhead needs to be benchmarked, and then subtracted if we're going to get some reasonable time - but we then run the risk of outliers giving us dumb results (e.g. benchmark for reseting state took more time than the subject for some reason).

In general, I think it's better to benchmark the round-trip - the value is in comparison anyway, and it's possible to benchmark the state-reset separately.

It might be nice to be able to specify in a report that the time from one subject should be deducted against that of another. Which would effectively be very similar to the example above.

**Comment by dantleech** [comment]
closing now as ths is quite old

> that can be measured and excluded from the output measurements.

i would just include the overhead, any attempt to measurement would vary significantly anyway, you could even end up with a neagative result.

saying that -- i wonder if something could be done with the new expression language : `mode(variant.time.avg) - mode(subject[name=overheadMethod]).variant.time.avg)` (that isn't supported)
