### ISSUE TITLE
Check if git command is available in \PhpBench\Environment\Provider\Git

### ISSUE THREAD

**Issue by sandrokeil** [phpbench/phpbench#317]
I'm using Docker to run the benchmarks and no git is installed. Is it possible to check if the git command is available, otherwise skip this provider?

**Comment by dantleech** [comment]
Yeah, it should certainly work without git.

I think the best place to do this would be [here](https://github.com/phpbench/phpbench/blob/master/lib/Environment/Provider/Git.php#L34).

**Comment by dantleech** [comment]
Fixed.

**Comment by sandrokeil** [comment]
Awesome. Thank you very much. :+1:
