### ISSUE TITLE
Remote Reflector could not read class name

### ISSUE THREAD

**Issue by sandrokeil** [phpbench/phpbench#325]
@dantleech The `\PhpBench\Benchmark\Remote\Reflector::getClassNameFromFile` could not read the class name, if the class name statement is on line 21. Not sure why this is happened in [\PhpBench\Benchmark\Remote\Reflector::getClassNameFromFile](https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Remote/Reflector.php#L122).

I've the following bench class in which occurs the error *Could not find class in file "/app/benchmarks/ClassMethodsHydratorBench.php"*. If I add one more line before the class statement, it works.

```php
<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/zf2 for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace ZendBench\Hydrator;

use Zend\Hydrator\ClassMethods;
use ZendBench\Hydrator\Asset\ClassMethodsObject;

/**
 * @BeforeMethods({"classSetUp"})
 * @Revs(1000)
 * @Iterations(20)
 * @Warmup(2)
 */
class ClassMethodsHydratorBench
{
    // code
}
```

**Comment by dantleech** [comment]
It reads the file in 20 lines chunks, so probably something trivial. Will have a look.

**Comment by dantleech** [comment]
Fixed!
