### ISSUE TITLE
GIT storage wrapper.

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#333]
Storage drivers may create files (e.g. the sqlite driver, or a hypothetical plain text storage driver). These files could be stored in GIT, providing a reliable history for the project.

A git wrapper would wrap an existing storage driver (implementing `FileAwareInterface` or whatever) and provide a path to the (or _a_) git repository, branch, commit and whatever.

See #252 for ideas on implementation.

**Comment by Ocramius** [comment]
> A git wrapper would wrap an existing storage driver (implementing `FileAwareInterface` or whatever) and provide a path to the (or a) git repository, branch, commit and whatever.

It could also simply wrap around any other storage adapter:

```php
$wrapper = new GitStorageWrapper(
    new XmlStorage($path)
);

$wrapper->save($results); // causes an implicit git add + git commit
```

In order to make this work, one could simply run a `git diff` before the wrapped storage `save` is called, then a `git diff` after the wrapped storage `save` is called: files that were modified by this procedure are to be saved.

**Comment by dantleech** [comment]
There are two things I am not sure of, firstly how we should handle the GIT branch/checkin/push.

We could do it in the `cwd` (i.e. the users project directory) and:

1. stash changes 
2. checkout the `phpbench_history` branch
3. do stuff
4. re-checkout the users branch
5. `git stash pop`.

but I worry that something goes wrong at `3` and the user gets confused and loses work.

For this reason I was *thinking* of locally cloning to `$XDG_DATA/phpbench/<project-name>` and doing all the work there.

Another thing that I am not sure of is how efficient GIT stores `.sqlite` files (the current storage implementation). An XML storage layer presents new problems/questions (how efficient is it to store these rather large files, querying over multiple documents, etc.). If you think an XML driver is worth it, lets create an issue for that.

In the last resort we could dump/backup the XML to the GIT branch (we can already serialize and deserialize from XML) and add the ability to restore to the storage driver.

**Comment by Ocramius** [comment]
> For this reason I was thinking of locally cloning to `$XDG_DATA/phpbench/<project-name>` and doing all the work there.

Same reasoning here

 > Another thing that I am not sure of is how efficient GIT stores `.sqlite` files (the current storage implementation). 

Not well: should be a text-based storage :-\

 > rather large files

Not really a big issue for GIT

**Comment by dantleech** [comment]
Created an issue for XML storage #338
