### ISSUE TITLE
Try appveryor for windows builds?

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#339]
http://www.appveyor.com/

**Comment by WyriHaximus** [comment]
:+1: if you want to support windows. Very easy to set up and since their move to a new platform a lot faster. Can file a PR if you want

**Comment by dantleech** [comment]
Please do! It does work on windows but as windows isn't designed to
create processes fast it is quite slow.

**Comment by WyriHaximus** [comment]
Sure, could you enable make sure this repository is enabled on AppVeyor? Also please make sure that `Skip branches without appveyor.yml` is enabled on https://ci.appveyor.com/project/phpbench/phpbench/settings (near the bottom). This will make sure Appvoyer doesn't try to build any branches that don't have the `appveyor.yml` file. Could you let me know once you've done that, I'll make the PR after that to ensure it will run tests there from the first commit :+1:

**Comment by dantleech** [comment]
I don't seem to be able to create the appveyor project for some reason.. http://help.appveyor.com/discussions/problems/5168-organization-not-being-shown-when-creating-a-new-project

**Comment by WyriHaximus** [comment]
Go to https://github.com/organizations/phpbench/settings/oauth_application_policy and check it AppVeyor is present and allowed there. Or try to reauth and make sure that the phpbench or is allowed, Github will show a list of orgs on the page you click `authorize`.

**Comment by dantleech** [comment]
ok, sorted :) Have created the project and enabled `Skip branches without appveyor.yml`.

**Comment by WyriHaximus** [comment]
Cheers I'll submit a PR soon

**Comment by WyriHaximus** [comment]
PR up at #438, might need some tweaking but it's a start :smile:
