### ISSUE TITLE
Writing custom renderers

### ISSUE THREAD

**Issue by yuloh** [phpbench/phpbench#397]
Hello,

I'm trying to write a custom renderer but I'm not really sure how to use it with phpbench.  I tried specifying my renderer in phpbench.json and it complained that it isn't in the registry.

Do I need to write an actual extension and load it from that?

Thanks!

- Matt

**Comment by dantleech** [comment]
Hi,

You need to create an Extension [example](https://github.com/phpbench/phpbench/blob/master/extensions/xdebug/lib/XDebugExtension.php)

and register it in your `phpbench.json`, [example](https://github.com/phpbench/phpbench/blob/master/phpbench.json.dist#L6)

and add the renderer with the following tag: `report_renderer` ([example](https://github.com/phpbench/phpbench/blob/master/lib/Extension/CoreExtension.php#L430))

hope that helps :)

**Comment by yuloh** [comment]
Perfect, thanks so much!
