### ISSUE TITLE
Progress logger looks bad with long names

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#414]
```

\Bench\BenchArrayChangeKeys

    benchSimpleLoopArrayKeyChangingI99 P0   [μ Mo]/r: 31.645 29.999 (μs)  [μSD μRSD]/r: 3.125μs 9.87%
    benchArrayCombineArrayKeyChangingI99 P0     [μ Mo]/r: 56.252 53.922 (μs)  [μSD μRSD]/r: 4.155μs 7.39%
    benchArrayChangeKeys          I99 P0    [μ Mo]/r: 49.162 47.321 (μs)  [μSD μRSD]/r: 3.772μs 7.67%
```

**Comment by Isinlor** [comment]
As a quick fix I would suggest removing bench prefix from the output, maybe moving the legend to the top. I can make a pull request if the changes would be fine with you.

It would look like that:
```
\Benchmarks\Constraint\Soft\MinimalDispersionConstraintBench

                                                                [μ Mo]/r:              [μSD μRSD]/r:
    AddSolution                                       R3 I9 P0 	9.308 9.417 (μs) 	    0.160μs 1.72%
    GetTotalPenalty                                   R1 I8 P0 	28.986 29.132 (μs) 	0.561μs 1.93%
```

**Comment by dantleech** [comment]
Indeed - my hesitation for that is because `bench` is not mandatory (you can use `@Subject` annoatation to indicate a benchmark method), so arbitrarily stripping it might produce undesirable results in some edge cases. So any such modification should probably check for the presence of the `@Subject` annotation.
