### ISSUE TITLE
ParamProviders Could Use Some Documentation Improvements

### ISSUE THREAD

**Issue by chrisguitarguy** [phpbench/phpbench#427]
The single param provider example seems incorrect.
<img width="445" alt="screen shot 2016-06-30 at 3 12 33 pm 1" src="https://cloud.githubusercontent.com/assets/1010392/16500974/1ee522b0-3ed5-11e6-932e-02e820e6630d.png">

Seems like it should be (based on the other examples and some experiments):

```php
public function provideStrings()
{
  return [
    ['string' => 'Hello World!'],
    ['string' => 'Goodbye Cruel World!'],
  ];
}
```

Additionally, it'd be good to document that on values that can be serialized to and from JSON can be used. My first instinct was to use param providers to benchmark a system with two different implementations of a dependency, which didn't work and didn't error in any way.

**Comment by dantleech** [comment]
hmm, the documented example should work, e.g.

```php
    /**
     * @Revs(1000)
     * @Iterations(5)
     * @paramProviders({"foobar"})
     */
    public function benchFalsey()
    {
        !$this->zero;
        !$this->full;
    }

    public function foobar()
    {
        return [
            [
                'hello' => 'foo',
                'goodbye' => 'bar',
            ]
        ];
    }
```

Works fine for me.

We do seem to be missing validation however.

**Comment by chrisguitarguy** [comment]
It works, @dantleech, but the `$params` passed into the `bench*` method are...

```php
[
  'hello' => 'Hello World!',
  'goodbye' => 'Goodbye Cruel World!'
]
```

Which doesn't match how the value is used in the `bench*` method right next to it in the docs:

![screen shot 2016-07-01 at 7 56 39 am](https://cloud.githubusercontent.com/assets/1010392/16520914/7172cd70-3f61-11e6-88aa-f47e46fbc369.png)

**Comment by dantleech** [comment]
I see, we should endevour to add type validation (which I thought already existed, but it seems to have been lost in refactoring) and fix those docs. will do it before the next release :)
