### ISSUE TITLE
MySQL with DBAL (--store)

### ISSUE THREAD

**Issue by danigulyas** [phpbench/phpbench#433]
Hey!:)

I really appreciate the hard work you guys do building this awesome library!:)

Today i've configured it with our CI and encountered a problem with the DBAL storage plugin with MySQL:

```
[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'INSERT INTO variant (revolutions, retry_threshold, output_time_unit, output_time_precision, output_mode, sleep, warmup, subject_id, run_id) VALUES (?, ?, ?, ?,
  ?, ?, ?, ?, ?)' with params [1, null, null, null, null, 0, 0, "1", "3"]:
  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value
```

For a couple of tables, the "migrate" script creating the schema is not setting up the `auto_increment` for the `id` fields, here's the sql i've ran to fix it:

```
alter table run change id id int(11)AUTO_INCREMENT;
alter table environment change id id int(11)AUTO_INCREMENT;
alter table subject change id id int(11)AUTO_INCREMENT;
alter table variant change id id int(11)AUTO_INCREMENT;
```

You might want to add these lines or edit the original creations to label `id` fields `auto_increment`al.

Enjoy your day!:)
Regards,
-Daniel

**Comment by dantleech** [comment]
Thanks, I think the CI tests run on sqlite, which might explain it. Will have a look,

**Comment by dantleech** [comment]
Hmm, we already specify the autoincrement: https://github.com/phpbench/phpbench/blob/master/extensions/dbal/lib/Storage/Driver/Dbal/Schema.php

Strange ..

**Comment by dantleech** [comment]
Have checked, and cannot reproduce this problem locally:

Doctrine DBAL:

```
$ composer show --installed
# ...
doctrine/dbal                       v2.5.4 
```

MySQL (MariaDB):

```bash
$mysql --version
mysql  Ver 15.1 Distrib 10.0.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by dantleech** [comment]
@danigulyas any update on this?

**Comment by danigulyas** [comment]
@dantleech Nope, cannot reproduce it by now (change of company). :/
