### ISSUE TITLE
Is it possible to setup iterations and revs in phpbench.json?

### ISSUE THREAD

**Issue by Isinlor** [phpbench/phpbench#437]
Is it possible to setup iterations and revs in phpbench.json?

I would want to shorten this `bin/phpbench run --iterations=10 --revs=1000` to `bin/phpbench run`, so that by default iterations and revs are read from phpbench.json. It is possible only with retry threshold.

**Comment by dantleech** [comment]
You can specify them with annotations.

    /**
     * @Iterations(10)
     * @Revs(100)
     */
    public function benchFoo() { }

**Comment by Isinlor** [comment]
Yes, indeed. But this setting is per benchmark and I want to use default for all benchmarks without need of specifying it per benchmark.

**Comment by dantleech** [comment]
Well it becomes difficult then as I see it - as the configuration would
override the per-benchmark settings. I suppose we could make the
configured values the defaults (so per-benchmark would override) -- this
would be made more valuable when "suites" are introduced (i.e. being
able to define a set of benchmarks with certain settings).

What do you think?

**Comment by Isinlor** [comment]
How does the console options behave? Shouldn't it work simply the same way?

My use case may not be the most popular one for PHP as I solve NP-hard problem similar to [Nurse Scheduling Problem](https://en.wikipedia.org/wiki/Nurse_scheduling_problem). I don't really care how many iterations and revisions is run per benchmark as long as I can quickly estimate if my changes speed up or slow down and by how much my algorithm.

The more specific setting overwriting the default ones probably make sense, but I don't see myself using them at all.

**Comment by dantleech** [comment]
Of course the other option is to simply extend all of your benchmarks
from a common parent class. You can then apply the
iterations/revolutions at the class level of the parent class.

```
/**
 * @Iterations(20)
 * @Revs(10000)
 */
abstract class BaseBenchmark
{
}
```

**Comment by dantleech** [comment]
Does the solution above solve your issue?

**Comment by Isinlor** [comment]
Yes, sorry I did not answer. The fact that console options overwrite annotation solves my problem since I already use an abstract base class.
Thank  you 👍 !

**Comment by dantleech** [comment]
Perfect :)
