### ISSUE TITLE
Resources are not available with @BeforeMethods

### ISSUE THREAD

**Issue by ogmueller** [phpbench/phpbench#443]
I am trying to initialize some hash contexts (resources) as a #BeforeMethods, but it won't let me use it, because something is changes them.

I attached a file and both bench functions should actually work, because they are using exactly the same code, except that one of them is using @BeforeMethods to initialize the hash, the other one is not.

[PhpHashBench.php.txt](https://github.com/phpbench/phpbench/files/447555/PhpHashBench.php.txt)

**Comment by dantleech** [comment]
The issue would seem to be that "init" is called once per iteration. When executing your benchmark with revs = 1 there is no issue, running with revs > 1 causes a resource error:

```
\PhpHashBench::benchHashFinalWithInit

    RuntimeException Benchmark made some noise: 
    Warning: hash_final(): supplied resource is not a valid Hash Context resource in /home/daniel/www/phpbench/phpbench/PhpHashBench.php on line 52
    
    Call Stack:
        0.0002     368952   1. {main}() /tmp/daniel/PhpBenchoeOxVX:0
        0.0071     885936   2. benchmark() /tmp/daniel/PhpBenchoeOxVX:41
        0.0071     885712   3. PhpHashBench->benchHashFinalWithInit() /tmp/daniel/PhpBenchoeOxVX:71
        0.0071     885712   4. hash_final() /home/daniel/www/phpbench/phpbench/PhpHashBench.php:52
```

So it would seem you perhaps cannot use the same hash resource multiple times?

**Comment by ogmueller** [comment]
That could be right. mmmh...is there any way i can determine how many rev and its there are going to be, so i can prepare my data accordingly? and determine in which one i am right now?
I had this problem a couple of times already and i can't do use my predefined number of revs, because they might change with the console parameter, right?

**Comment by dantleech** [comment]
They can be overridden by the console parameter.

You can keep track of the revs locally, f.e.:

```
public function __construct()
{
    $this->revIndex = 0;
}

public function benchFoo()
{
    $this->revIndex++;
}
```

This will add the overhead of incrementing the variable, but if you are
benchmarking algorithms this will presumably be irrelevant :)

**Comment by ogmueller** [comment]
Great idea. Then i know in which rev i am! Thnx.

But how can i prepare the data? I need to know how many revs and its are going to come in the provider function. I also had that problem, when i tried to test a function which reduces the file size :-)

**Comment by dantleech** [comment]
There is currently no way to determine how many revolutions are being executed from within the benchmark ..  potentially we could inject the number of revolutions and other variables into the contructor of the benchmark with no overhead: 

https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Executor/template/microtime.template#L27

If we add arguments to the contructor (or whatever) its a change that can have BC implications in the future, so we will have to think about it and ensure that it is a required feature.

Can you describe your file-size use case?

**Comment by ogmueller** [comment]
The file size example is just one way to explain a general problem, if someone doesn't know how many revs and its will come.

So let's say you want to benchmark the internal PHP function "ftruncate". Than you have two options:

- you create a file and then truncate it within a single method benchFtruncate()
- you prepare a file in a @BeforeMehtods and then  truncate it in benchFtruncate()

The problem with the first solution is, that you measure way too much, because file creation takes a lot of time.
The problem with the second solution is, that you don't know, how big your file has to be. If you only truncate one byte per iteration, you might need only 10kB or 1MB depending on revs and its.

**Comment by dantleech** [comment]
> The problem with the second solution is, that you don't know, how big your file has to be. If you only truncate one byte per iteration, you might need only 10kB or 1MB depending on revs and its.

Why would the filesize depending on `@Revs` ? It would be constant if created in `@BeforeMethods` or?

**Comment by ogmueller** [comment]
The file size you need depends on how often the benchmark method is called. So if the iterations are set to 1000 and you create a file with >=1k everything is fine. But if someone is increasing the iterations with a CLI option, than it will fail.

**Comment by dantleech** [comment]
ok. so for each revolution you truncate 1 byte from the file? I guess that is a valid use case, will have a think but I think we could inject an array of parameters to the constructor of the BM.

**Comment by ogmueller** [comment]
Oh sorry, I am always mixing up revs and iterations :-) it is exactly as you said.

**Comment by dantleech** [comment]
So just to be sure here: the solution would be to let the `@BeforeMethod` know about the context of the benchmark (e.g. iterations, revs, etc)?

**Comment by dantleech** [comment]
See https://github.com/phpbench/phpbench/issues/462 for possible solution, closing this. Feel free to reopen if that issue does not provide a solution.
