### ISSUE TITLE
Memory limit specified in php_config is ignored

### ISSUE THREAD

**Issue by ezzatron** [phpbench/phpbench#481]
I have this config:

```json
{
    "bootstrap": "vendor/autoload.php",
    "php_config": {
        "memory_limit": "1G"
    }
}
```

And one of my benchmarks is failing with this message:

```
  [RuntimeException]
  Cannot retrieve stats when an exception was encountered ([PhpBench\Benchmark\Remote\Exception\ScriptErrorException]
  Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in /path/to/phony-benchmarks/vendor/phpdocumentor/type-resolver/src/Types/ContextFa
  ctory.php on line 72
  )
```

The allowed memory size value of 134217728 bytes mentioned in the exception is only 128M, which is my system default.

I'm running `"phpbench/phpbench": "^0.13"` under `PHP 7.1.8` installed via Homebrew on macOS Sierra.

**Comment by dantleech** [comment]
Will have to debug the exact command that is executed: https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Remote/Payload.php#L114

**Comment by torinaki** [comment]
@ezzatron seems I have faced with similar issue in #488. As I mentioned in #488 it happens, because of MicrotimeExecutor behavior.

**Comment by dantleech** [comment]
Created #489 to handle the PHP config issue.
