### ISSUE TITLE
Provide possibility to enable OpCache and disable Xdebug by default

### ISSUE THREAD

**Issue by torinaki** [phpbench/phpbench#488]
I have faced with two issues while trying to migrate my benchmarks to PhpBench and get same numbers:

1. The are no possiblity to disable XDebug out-of-the box. For example Composer creates temporary php.ini:
https://github.com/composer/composer/blob/ff61ecd484d4e280e9892c13de3531a6a115aeed/src/Composer/XdebugHandler.php
At least warning message must be shown.
2. OpCache is disabled in CLI by default. It will be great to force to enabled it, because it may positively affect PHP performance due to OpCache binary code optimization. Usualy on production it is enabled by default(in context of WEB page).

I can't enable OpCache from phpbench.json, because MicrotimeExecutor overrides PHP configurations.

**Comment by dantleech** [comment]
> The are no possiblity to disable XDebug out-of-the box

No indeed. I like the idea of having a separate INI file, and it would be easier here as we always launch new PHP processes anyway. Will have a thinkl.

> OpCache is disabled in CLI by default

Sounds like we can fix this easily by addressing #481 ?

**Comment by torinaki** [comment]
@dantleech 
1. Agree it is an option. In this case you must execute: `php -n -c ./custom-php.ini /tmp/Phpbench...`. But anyway it would be better to add some notification that benchmark absolute time values will be higher that usual. Hope that relative values is not affected by XDebug, because all absolute time values increases in same proportion. 
2. Sounds good 👍

**Comment by dantleech** [comment]
I have created: https://github.com/phpbench/phpbench/pull/490

This allows you to disable the PHP ini file.

I'm not sure we should show warnings about XDebug, as that assumes that the user is not trying to benchmark _with_ XDebug, and that no other extensions would slow down the benchmark.

The `--report=env` does identify if xdebug is loaded, and lists all of the loaded extensions.

**Comment by torinaki** [comment]
@dantleech I have take a look on you PR. Everything is addressed. Thanks you very much!

It would be great to add notice about OpCache into docs as well.
OpCache is disabled by default, due to we run benchmarks from CLI. To enable OpCache for CLI you must set `opcache.enable_cli=1` in [config](http://php.net/manual/en/opcache.configuration.php#ini.opcache.enable-cli).

In my benchmarks OpCache positively affects memory usage and probably it may affects CPU usage as well.

**Comment by torinaki** [comment]
@dantleech here is one reference about OpCache affecting memory usage:
https://nikic.github.io/2015/06/19/Internal-value-representation-in-PHP-7-part-2.html#arrays

**Comment by dantleech** [comment]
I experimented a bit with opcache, and made a PR to add an [opcache env provider](https://github.com/phpbench/phpbench/pull/492), which basically says if the opcache is enabled or not (I did show all the stats from `opcache_get_stats` but as the env. providers are run at the begining of the request, it was rather pointless).

I'm not sure if we should recommend to enable opcache - it certainly does have an impact though - maybe we should add another section to the docs, "recommendations" or something...

**Comment by torinaki** [comment]
@dantleech looking on current documentation structure "recommendation" section probably is good candidate.
In my point of view such conceptual configurations must be part of benchmarking methodology. Unfortunately documentation does not provide an example of such.

**Comment by dantleech** [comment]
I created an issue #541  for reviewing / refactoring the documentation for the 1.0 release, and will add a new section "Best Practices" or "Recommendations".

Feel free to continue this discussion there.
