### ISSUE TITLE
Benchmarks with params series

### ISSUE THREAD

**Issue by torinaki** [phpbench/phpbench#493]
Is it possible to create easely configurable params to create benchmarks that can show performance dynamics over different params series?

For example to build graphs to show memory or CPU time consumption over different param series
https://twitter.com/nikita_ppv/status/847855830821109760

@ParamProviders do not fit in this case, because it can provide only scalars directly inside bench methods:
http://phpbench.readthedocs.io/en/latest/writing-benchmarks.html?highlight=beforemethod#parameterized-benchmarks

Currenlty I'm using @BeforeMethods to prepare data, but there no possibility to pass any params into this method. It would be great to introduce some kind of @MatrixParamProviders for class that will be passed into @BeforeMethods with all possible permutation

**Comment by dantleech** [comment]
`beforeMethod` [does](https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Executor/template/microtime.template#L28) get called with the parameters.

And you can combine multiple param providers into a cartesiant product (matrix) ([docs](https://phpbench.readthedocs.io/en/latest/writing-benchmarks.html#parameterized-benchmarks))

**Comment by dantleech** [comment]
There are still lots of improvements to be made for this use case though, I would like to see:

- Param generators (e.g. a range)
- [Graph rendering](https://github.com/markrogoyski/math-php/pull/170)

Any other ideas welcome :)

**Comment by torinaki** [comment]
@dantleech thanks you for explanation. Seems I have missed this part in [documentation](https://phpbench.readthedocs.io/en/latest/writing-benchmarks.html#subject-runtime-state-before-and-after).

**Comment by dantleech** [comment]
Cool, closing for now. Feel free to reopen if necessary.
