### ISSUE TITLE
Comparing two dump-files does not work

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#508]
To reproduce:

    phpbench --report=aggregate --dump-file=fileA.xml --context="A"
    phpbench --report=aggregate --dump-file=fileB.xml --context="B"

    phpbench report --file=fileA.xml --file=fileB.xml --report=compare

right from the docs.

	[InvalidArgumentException]
	  Column "vcs_branch" does not exist, valid columns: "suite", "date", "stime", "benchmark_full", "groups", "params", "revs", "its", "mem_real", "mem_final", "mem_peak", "min", "max", "sum", "stdev", "mean", "mode", "variance", "rstdev", "best", "worst", "uname_os", "uname_host", "uname_release", "uname_version", "un
	  ame_machine", "php_version", "php_xdebug", "baseline_nothing", "baseline_md5", "baseline_file_rw"  	
    Exception trace:
	 PhpBench\Report\Generator\Table\Row->offsetGet() at C:\project\vendor\phpbench\phpbench\lib\Report\Generator\TableGenerator.php:261
	 PhpBench\Report\Generator\TableGenerator->PhpBench\Report\Generator\{closure}() at C:\project\vendor\lstrojny\functional-php\src\Functional\Map.php:43
	 Functional\map() at C:\project\vendor\phpbench\phpbench\lib\Report\Generator\TableGenerator.php:265
	 PhpBench\Report\Generator\TableGenerator->PhpBench\Report\Generator\{closure}() at C:\project\vendor\lstrojny\functional-php\src\Functional\Map.php:43
	 Functional\map() at C:\project\vendor\phpbench\phpbench\lib\Report\Generator\TableGenerator.php:266
	 PhpBench\Report\Generator\TableGenerator->processCols() at C:\project\vendor\phpbench\phpbench\lib\Report\Generator\TableGenerator.php:106
	 PhpBench\Report\Generator\TableGenerator->generate() at C:\project\vendor\phpbench\phpbench\lib\Report\ReportManager.php:56
	 PhpBench\Report\ReportManager->generateReports() at C:\project\vendor\phpbench\phpbench\lib\Report\ReportManager.php:84
	 PhpBench\Report\ReportManager->renderReports() at C:\project\vendor\phpbench\phpbench\lib\Console\Command\Handler\ReportHandler.php:41
	 PhpBench\Console\Command\Handler\ReportHandler->reportsFromInput() at C:\project\vendor\phpbench\phpbench\lib\Console\Command\ReportCommand.php:87
	 PhpBench\Console\Command\ReportCommand->execute() at C:\project\vendor\symfony\console\Command\Command.php:252
	 Symfony\Component\Console\Command\Command->run() at C:\project\vendor\symfony\console\Application.php:936
	 Symfony\Component\Console\Application->doRunCommand() at C:\project\vendor\symfony\console\Application.php:240
	 Symfony\Component\Console\Application->doRun() at C:\project\vendor\symfony\console\Application.php:148
	 Symfony\Component\Console\Application->run() at C:\project\vendor\phpbench\phpbench\lib\PhpBench.php:58
	 PhpBench\PhpBench::run() at C:\project\vendor\phpbench\phpbench\bin\phpbench.php:24
	 require() at C:\project\vendor\phpbench\phpbench\bin\phpbench:4

**Comment by dantleech** [comment]
Possible that one didn't have a VCS when the dump was taken? But this should be handled.

On 5 January 2018 01:10:01 CET, Frank Hein <notifications@github.com> wrote:
>To reproduce:
>
>    phpbench --report=aggregate --dump-file=fileA.xml --context="A"
>    phpbench --report=aggregate --dump-file=fileB.xml --context="B"
>
>    phpbench report --file=fileA.xml --file=fileB.xml --report=compare
>
>right from the docs.
>
>Result:
>Column "vcs_branch" does not exist, valid columns: "suite", "date",
>"stime", "benchmark_full", "groups", "params", "revs", "its",
>"mem_real", "mem_final", "mem_peak", "min", "max", "sum", "stdev",
>"mean", "mode", "variance", "rstdev", "best", "worst", "uname_os",
>"uname_host", "uname_release", "uname_version", "un
>ame_machine", "php_version", "php_xdebug", "baseline_nothing",
>"baseline_md5", "baseline_file_rw"
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbench/phpbench/issues/508

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantleech** [comment]
Confirmed

**Comment by dantleech** [comment]
Addressed in #509 - we should really be using env-specific columns in default reports

**Comment by fhein** [comment]
@dantleech: Thank you. :) But different from the docs the report shows suite's uuid headings, not the context.

**Comment by dantleech** [comment]
Where abouts in the docs?

**Comment by fhein** [comment]
[BenchMarkRunner](https://phpbench.readthedocs.io/en/latest/benchmark-runner.html)
Says:

	Comparing Results
	You can compare the results of two or more sets of results using the compare report.

	First you should generate a suite result document for each separate implementation and specify a context:

	$ # .. configure for implementation A
	$ phpbench run --context="Impl. A" --dump-file=impl-a.xml
	$ # .. configure for implementation B
	$ phpbench run --context="Impl. B" --dump-file=impl-b.xml
	$ # .. configure for implementation C
	$ phpbench run --context="Impl. C" --dump-file=impl-c.xml
	Now you can use the report command and specify the compare report to compare the results for each implementation side-by-side:

	$ phpbench report --file=impl-a.xml --file=impl-b.xml --file=impl-c.xml --report=compare
	+---------+------------------+----------+---------+--------+-----------+-----------+-----------+
	| context | benchmark        | subject  | group   | params | t:Impl. A | t:Impl. C | t:Impl. B |
	+---------+------------------+----------+---------+--------+-----------+-----------+-----------+
	| Impl. A | HashingBenchmark | benchMd5 | hashing | []     | 2.4448µs  | 4.3039µs  | 1.5003µs  |
	+---------+------------------+----------+---------+--------+-----------+-----------+-----------+

**Comment by fhein** [comment]
btw: can I add a computed column (difference in percent or so)?

**Comment by fhein** [comment]
Suggestion: Doesn't this look a bit more pretty for comparison?
    'break' => ['benchmark']

**Comment by dantleech** [comment]
> btw: can I add a computed column (difference in percent or so)?
Not currently

> Suggestion: Doesn't this look a bit more pretty for comparison?

I guess that might be a better default.

**Comment by fhein** [comment]
Are contributions welcome?

**Comment by dantleech** [comment]
of course ! :)
