### ISSUE TITLE
Proposal for a comparison report 

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#512]
Here's an example of the comparison report I am looking for. I manually adjusted
the standard output of compare..

I think this could be a nice standard offering.

Changed the headers to display suite:context instead of suite:uuid.
Added a column called gain, but 'factor' or such would be better, maybe?

	benchmark: SetNewServicesBench
	+------------------------+--------------------+------------------+--------+
	| subject                | suite:develop:mean | suite:PR221:mean | gain   |
	+------------------------+--------------------+------------------+--------+
	| benchSetService        | 1.924µs            | 0.655µs          |  2,94x |
	| benchSetFactory        | 4.183µs            | 1.226µs          |  3,41x |
	| benchSetAlias          | 11.222µs           | 1.872µs          |  5,99x |
	| benchSetAliasOverrided | 34.617µs           | 1.876µs          | 18,45x |
	+------------------------+--------------------+------------------+--------+

In this case the left mean column is the base column and the gain is left:mean/right:mean.
It would be ok, if the first --file param would be taken as base. Deluxe would be a command line parameter taking the number of the --file param which to take as base. But that's deluxe.

Sorting by gain should be possible. I believe, that that already will be possible, once the column exists.

If there are more than two suites compared the column structure could be

    mean:base | mean:1 | gain:1 | mean:2 | gain:2 ...

I don't think, that computation of an average gain or such would provide meaningful information. We don't know the call distribution for the several APIs in user scenarios.

**Comment by dantleech** [comment]
The problem is that you can compare more than 2 things. My original plan was to have `0.655µs (+1.15%)` for each column, but it's not _currently_ possible with the current framework.

**Comment by fhein** [comment]
To be able two compare exactly two reports would be sufficient for now. Please, please? :)

To support more than two would mean, to run comparisons of two several times. The aggregated report would take all columns from the first run, and the last two of each consecutive run. But that would be deluxe also.

With the comparison of two in place I can manually run consecutive comparisons. But I could put my calculator back into the drawer. ;)

**Comment by fhein** [comment]
I think factor is more expressive than percent. Percent value diffs are more difficult to understand, if they reach the thousands. ;)

**Comment by fhein** [comment]
Ah, I see. 

Comparing several reports could mean: Compare all against designated base. Not all against each other.

**Comment by dantleech** [comment]
Yeah, the problem is is not currently not possible to do what I show above (format `<microseconds>µs (x<multiplier)`).

**Comment by popnikos** [comment]
I just see this issue about report comparison. 
This could be great to be able to compare reports (using the log command) 
May be using highlighting for time/mem_peak lost or gain

**Comment by dantleech** [comment]
See https://github.com/phpbench/phpbench/pull/648 - assuming this fixes the issue here? if not please reopen
