### ISSUE TITLE
Please remove 'assertions-asserters.rst:3:' file

### ISSUE THREAD

**Issue by codejam1024** [phpbench/phpbench#513]
Windows isn't supported?
'/docs/assertions-asserters.rst:3:'

**Comment by dantleech** [comment]
Removed. Phpactor should support Windows, does it not?

**Comment by codejam1024** [comment]
Do you have any updates with Phpactor project?

**Comment by dantleech** [comment]
Check https://twitter.com/phpactor for updates to that project. Windoes should be supported, please reopen this ticket if that is not the case :)

**Comment by codejam1024** [comment]
Fix with:
composer update phpbench/phpbench

**Comment by dantleech** [comment]
Sorry, I don't understand what the issue is here. Note that this is the PHPBench repository, not Phpactor. If updating PHPBench fixed Phpactor for you, please explain why.

**Comment by codejam1024** [comment]
Still getting the old PHPBench in Phpactor. After the manual update, it works!
