### ISSUE TITLE
Pathes under Windows

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#516]
Support for Windows is better now. :) But there are still some issues left regarding filename and path handling:

1. If the path to the PHP executable used contains spaces, this causes an error. This happens with Zend Studio installations for example, where the path to the built-in PHP is something like 

        C:\Program Files\Zend\Zend Studio 13.6.1\plugins\com.zend.php.executables.windows_7.1.3.201703171134\resources

        Der Befehl "C:\Program" ist entweder falsch geschrieben oder
        konnte nicht gefunden werden. (Command not found or misspelled.)

2. Even having `benchmarks` configured as the location of the benchmark files in `phpbench.json`, you get an error if you omit that parameter on the command line.

         vendor\bin\phpbench run --report=aggregate

does not work while 

         vendor\bin\phpbench run benchmarks --report=aggregate

works.

**Comment by dantleech** [comment]
Hey, thanks for the report.

> If the path to the PHP executable used contains spaces, this causes an error. This happens with Zend Studio installations for example, where the path to the built-in PHP is something like

Unfortunately I don't have Windows, so can't check this. But it _should_ work with the latest version of PHPBench - can you check how [this line](https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Remote/Payload.php#L111) evaluates in this case?

> Even having benchmarks configured as the location of the benchmark files in phpbench.json, you get an error if you omit that parameter on the command line.

Do you get a specific error? Maybe having a look [here](https://github.com/phpbench/phpbench/blob/master/lib/Console/Command/Handler/RunnerHandler.php#L88) will suggest a solution?

**Comment by fhein** [comment]
I'll check the line you mentioned.

The specific error is

        File or directory "C:\_dev\Zend\zend-servicemanager\C:\_dev\Zend\zend-servicemanager/benchmarks" does not exist (cwd: C:\_dev\Zend\zend-servicemanager)

cwd gets duplicated.

**Comment by fhein** [comment]
The report was about 0.13.0. This gets installed via zend-servicemanager composer.json.
I changed that to dev-master, which installed 0.15-dev.
None of the problems reported occurs with that build. Sorry for the false alarm. :(

**Comment by dantleech** [comment]
Good news, will hopefully get 0.15 out soonish.
