### ISSUE TITLE
My quick hack to calculate the difference column as of #512

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#517]
Just want to share how I helped myself to add diff column to the comparison report. 

If I would like to contribute a some more sophisticated version  fully controllable via command line, would TableGenerator.php be the recommended level for such surgery?

Here's what I currently do:

Command line: 
     vendor\bin\phpbench report --file=..\all.050.xml --file=..\all.zend.xml --report="extends: compare, compare: tag, cols: ["benchmark", "subject"]

Hack in TableGenerator.php::processCompare:

    /**
     * Process the compare feature.
     *
     * @param array $tables
     * @param Config $config
     *
     * @return array
     */
    private function processCompare(array $tables, Config $config)
    {
        ...
                          // TODO: This probably means the field is non-comparable, could handle this earlier..
                        if (isset($this->classMap[$compareField])) {
                            // we invent a new col name here, use the compare field's class.
                            $this->classMap[$name] = $this->classMap[$compareField];
                        }
                    }
                }
                $table[] = $firstRow;
            }
            // hack begin
            foreach ($table as $row) {
                $row['diff'] = $row['tag:zend:mean'] / $row['tag:mxc:mean'];
            }
            $config['sort'] = [ 'diff' => 'desc'];
            $table = $this->processSort($table, $config);
            // hack end 

            $table = F\map($table, function ($row) use ($colNames) {
                $newRow = $row->newInstance([]);
        ...
    }

I can not currently use the sort parameter on the command line `sort: { diff: 'desc' }`, because processSort gets called first, i.e. before I patch the `diff` column in.

**Comment by dantleech** [comment]
Closing now, as differences are now displayed in progress output and reports.
