### ISSUE TITLE
PHIVE support

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [phpbench/phpbench#521]
Could you please add support for PHIVE?

PHIVE is a package manager to securely install PHARs.  So its composer for PHARs! 

You're already distributing signed PHARs, so you're almost set!

More information about PHIVE: https://github.com/phar-io/phive/
See https://phar.io/howto/sign-and-upload-to-github.html for a detailed How-To-Guide to bring Github releases automatically to PHIVE.

**Comment by dantleech** [comment]
Yes, that would be great. The only challenge would seem to be publishing to GH releases from Travis, but sure it's possible.

**Comment by dantleech** [comment]
Looks like Travis has added built-in support for releasing to GH since I implemented the self-updating PHAR: https://docs.travis-ci.com/user/deployment/releases

Will try and do this for the 1.0 release.

**Comment by dkarlovi** [comment]
Note: probably the easiest way to build a PHAR is using https://github.com/humbug/box (v3).

**Comment by dantleech** [comment]
Yep, we already have a PHAR :) https://phpbench.readthedocs.io/en/latest/installing.html#install-as-a-phar-package

**Comment by dkarlovi** [comment]
Oh, sorry, should have checked the source first. I've just checked the GH releases page.  :see_no_evil:

**Comment by dantleech** [comment]
https://github.com/phar-io/phar.io/pull/58/files ...

**Comment by dantleech** [comment]
Phive is now supported.
