### ISSUE TITLE
Provide own time measurements in benchmarks

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [phpbench/phpbench#527]
Is there a way for a benchmark to provide its own time measurements? E. g. with an extension or something?

My use-case is this: We have some benchmarks where we're using selenium / mink to benchmark page loading times on real browsers. This works like this (rough outline to make my point, dont nail me on the details pls):
- We tell the selenium-server to open an URL in a specific selenium-client (e. g. a chrome-browser client).
- The servers forwards our request to the client.
- The client opens the browser and loads the URL.
- **The browser finishes loading the page** and tells the selenium client that its ready.
- The selenium client tells the server that its ready.
- The selenium server tells our Benchmark that its ready.

The time that really matters in this situation is not the time from begin to end, but the time that the browser took loading the site. Everything else around it is just noise that can mask important performance differences.
Chrome gives us the possibilty to measure the page loading times via the [PerformanceTiming API](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming).

Example of one of our tests: the whole test took 2400 ms, but the page load only took 950 ms. The other 1450 ms are totally irrelevant to our benchmark...

But phpbench measures the whole execution time of my `benchX()` function. I need some way to in my bench-function to return my own time measurements (done via the Performance API).

Is there some way to achieve this?

**Comment by dantleech** [comment]
You can, you need to:

1. Create an extension
2. Implement an Executor (`ExecutorInterface`)
3. Tell PHPBench to use it.

Creating an extension is pretty easy - just check the `extensions` folder in the project root. The executor is also easy, checkout how the Executor is tagged in the XDebug extension's DI config.

Telling PHPBench to use it can be achieved with `phpbench run --executor="{executor:your_extension, param1: key1, param2: key2}"`.

I'm don't _think_ this can be done at the annotation level (or even at the global config level). But these would be low hanging fruit.

**Comment by dantleech** [comment]
... and I guess the benchmarking classes themselves would then simple be responsible
for providing the data for your executor:

```php
/**
 * @Executor('selenium');
 */
class MyWebSiteBench
{
    public function benchHomepage(): Request
    {
        return new Request('GET', '/', [
            'Header1' => 'Value1',
            'Header2' => 'Value2',
        ]);
    }
}
```

**Comment by MatthiasKuehneEllerhold** [comment]
Thank you very much. This worked pretty good!

Bonus-Question: is there a way to provide two time measurements for different things in one go?
E. g. a total browser load time and a DOM load time? Ive got them in my executor but calling `$iteration->setResult(new TimeResult(..))` a second time overwrites the previous value.

**Comment by dantleech** [comment]
Sure, just implement your own result class :)

**Comment by MatthiasKuehneEllerhold** [comment]
Oh sorry, I forgot to close this issue. Thank you very much for your help!

**Comment by dantleech** [comment]
No worries, let me know if you open source what you have :)
