### ISSUE TITLE
Consider dropping the `json` extension requirement

### ISSUE THREAD

**Issue by rybakit** [phpbench/phpbench#534]
According to the [documentation](http://phpbench.readthedocs.io/en/latest/configuration.html#disable-the-php-ini-file), you can't just disable *all* extensions from loading, `json.so` still needs to be included to be able to run benchmarks. I wonder if it's really mandatory or the benchmark-related code (templates?) can be refactored to use built-in `serialize/unserialze`? Besides the fact that it will make the configuration a bit clearer, it will probably solve issues with handling binary data (see this [SO question](https://stackoverflow.com/questions/29816007/sending-binary-file-content-using-json) or this [issue](https://github.com/phpbench/phpbench/issues/532)).

**Comment by dantleech** [comment]
Yeah, we certainly do want to drop the JSON dependency, f.e. https://github.com/phpbench/phpbench/issues/491 suggests we do it in plain text.

Using `serialize/unserialize` couples us to PHP, which might not be such a bad thing, but theoretically we could eventually delegate to non-PHP processes to obtain results.

**Comment by dantleech** [comment]
In #539 we replace `json_encode` with `serialize`
