### ISSUE TITLE
µ is garbled in windows7.

### ISSUE THREAD

**Issue by TonyChen-SH** [phpbench/phpbench#538]
\HashBench

    benchMd5                      I0 P0 	[u Mo]/r: 0.000 0.000 (渭s) 	[uSD uRSD]/r: 0.000渭s 0.00%
    benchSha1                     I0 P0     benchSha1                     I1 P0     benchSha1                     I2 P0     benchSha1                     I3 P0     benchSha1                     I4 P0 	[u Mo]/r: 1.210 1.165 (渭s) 	[uSD uRSD]/r: 0.092渭s 7.61%

2 subjects, 6 iterations, 100,001 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 0.000 [0.605 0.583] 0.000 (渭s)
鈪�T: 6.050渭s 渭SD/r 0.046渭s 渭RSD/r: 3.805%

**Comment by dantleech** [comment]
I don't use Windows, so no way to test this, but maybe [this](https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line/388500#388500) helps?

Also in general, it would be recommended not to use the Windows shell, but rather something _like_ [conemu](https://www.fosshub.com/ConEmu.html) I _think_.

**Comment by dantleech** [comment]
Any update on this? Are you using the Windows `cmd` shell?
