### ISSUE TITLE
Single target annotations `@BeforeMethod` insteadof `@BeforeMethods`

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#542]
Metadata such as:

```
@ParamProviders({"foo"})
@BeforeMethods({"one", "two})
@AfterMethods(...)
@BeforeClassMethods(..)
...
```

Accept multiple targets, but I think is rarely used. Hitting multiple targets can be easily done by delegating from a single target.

The ParamProvider might be a special case in that it produces a Cartesian product of all the given providers.

**Comment by scyzoryck** [comment]
Hi! 
Looking at the usage example, sometimes there might be useful to have more than one "Before" method, for example to split initialisation of data and classes: see:  [ivory-serializer-benchmark](https://github.com/php-serializers/ivory-serializer-benchmark/blob/master/src/AbstractBench.php). What do you think about `@Before` annotation for methods similar to PHPUnit?
