### ISSUE TITLE
Sanitize/calibrate functionality

### ISSUE THREAD

**Issue by rybakit** [phpbench/phpbench#545]
I try to figure out if I can replace my own benchmark micro-framework with phpbench. I did a cursory search on documentation and the [benchmarks-examples](https://github.com/phpbench/benchmarks-examples) repository but failed to find what would be the best way to reimplement sanitize/calibrate functionality within phpbench (for example, check [this class](https://github.com/rybakit/msgpack.php/blob/837963c0b9481085c5a1c9bf0d15dcf472dce2d1/tests/Perf/Target/PeclFunctionPackTarget.php) to see what I mean). Any suggestions?

**Comment by dantleech** [comment]
This type of "calibration" has been considered, and I commented on it just [recently](https://github.com/phpbench/phpbench/issues/304#issuecomment-390393678).

My concern with this approach however is that potentially (more?) liable to give false results, depending on how the calibration is obtained. We deduct the calibrated value from the main value, but it's perfectly possible that for unknown reasons the calibrated value is MORE than the main value (system state fluctuations) resulting in a negative time.

I am open to suggestions though, but unsure of the benefit? - all times are relative anyway.

**Comment by rybakit** [comment]
> all times are relative anyway.

Fair enough. Anyway, I can't come up with a reliable solution for system state fluctuations you have mentioned.

And what about "sanitizing" code before running benchmarks, to make sure it's valid (and skip it otherwise)?

**Comment by dantleech** [comment]
> And what about "sanitizing" code before running benchmarks

I like the idea of "sanitization" (or validation?). In Macro benchmarks (e.g. 10s of milliseconds) I actually just use PHPUnit assertions (because the cost of the Assert is insignificant). But for micro benchmarks this isn't a viable approach.

We could possibly have a solution where the method `returns` a value which can be validated in a separate method (you add the cost of `return` however, not sure how big that would be.

Or ... I would really like to implement in-lining benchmarks (removing the method call). In which case you could decorate it somehow.

**Comment by rybakit** [comment]
```php
/**
 * @validate({"validatePayload"})
*/
class MyPackerBench
{
    public function __construct()
    {
        $this->packer = new Packer();
    }

    public function benchPackInt(array $payload)
    {
        $this->packer->pack($payload['raw']);
    }

    public function benchPackFloat(array $payload)
    {
        $this->packer->pack($payload['raw']);
    }

    /**
     * @validate({"validateStrPayload"}) <-- override the class-level validate function
     */
    public function benchPackStr($payload)
    {
        $this->packer->pack($payload['raw']);
    }

    public function validatePayload(array $payload) : bool
    {
        return $this->packer->pack($payload['raw']) === $payload['packed'];
    }

   public function validateStrPayload(array $payload) : bool
   {
        // do str-specific validation
        // and then fall back to the global one:

        return $this->validatePayload($payload);
   }
}
```

I'm not familiar with phpbench internals, but would something like ^this^ work?

**Comment by dantleech** [comment]
It would. I wonder if we can use the existing `@Assert` annotations, e.g.

```
/**
 * @Assert(callback="validateStrPayload")
 */
public function benchFoo()
{
}
```

Assert was designed to assert the results (e.g. `< 1 second`) but if it's a callback you could put anything in there...

**Comment by dantleech** [comment]
Actually I wonder if it would suffice to simply throw an exception in `@BeforeMethod('validateStr')` ?

**Comment by rybakit** [comment]
Throwing an exception in `@BeforeMethod(s)` would mean that the entire benchmark will be stopped, am I right? What I would like to have is an ability to skip failed benchmarks and continue with valid ones. In my case, I want to benchmark two different libraries that are not 100% compatible (like one of the libraries has known bugs or/and lacks some functionality) and see how their common functionality is compared in terms of performance.

```php
/**
 * @BeforeMethods({"validateParams"})
 */
final class HashBench
{
    public function validateParams(array $params)
    {
        if (!isset($params['data'])) {
            throw new \UnexpectedValueException('Invalid parameter, the "data" key is missing.');
        }
    }

    /**
     * @Subject()
     * @ParamProviders({"provideParams"})
     */
    public function hash_md5(array $params)
    {
        hash('md5', $params['data']);
    }

    /**
     * @Subject()
     * @ParamProviders({"provideParams"})
     */
    public function hash_sha256(array $params)
    {
        hash('sha256', $params['data']);
    }

    /**
     * @Subject()
     * @ParamProviders({"provideParams"})
     * @BeforeMethods({"validateMyHash"})
     */
    public function hash_myhash(array $params)
    {
        my_hash($params['data']);
    }

    public function validateMyHash(array $params)
    {
        $result = my_hash($params['data']);

        if (!is_string($result) || '' === $result) {
            throw new \UnexpectedValueException("my_hash() returns wrong result for this set.");
        }
    }

    public function provideParams()
    {
        return [
            ['data' => 'foobar'],
            ['data' => 'bazqux'],
            ['data' => null],
        ];
    }
}

function my_hash(string $data)
{
    if ('bazqux' === $data) {
        return null;
    }

    return "hashed_$data";
}
```
So for the example above, phpbench can skip/ignore sets with `data = null` (for all benchmarks) and `data = bazqux` (for `hash_myhash`). This probably can be achieved by throwing a special `SkippedBenchmarkException` which can be hidden in a helper method, like `assertOrSkip()`. Does this make sense or am I going in the wrong direction?

**Comment by dantleech** [comment]
> Throwing an exception in @BeforeMethod(s) would mean that the entire benchmark will be stopped, am I right?

I think it will FAIL the subject that throws the exception and carry on with subsequent subjects, but it will be treated like an error (and what's more you can't generate a report when this happens - which is a bug).

> SkippedBenchmarkException

I think that could be good. We could presumably wrap the everything in a `try` `catch` do that `SkippedBenchmarkException` could be thrown from the `benchFoo` method.

If we do we might namespace them:

```
namespace PhpBench {
    class SkippedBenchmarkException extends \Exception {}
} 
```

Then we could catch them in the generated script (`microtime.template`) and pass back to Phpbench (which could in-turn throw a SkippedBenchmarkException of it's own and mark the whole variant as `skipped`).

**Comment by dantleech** [comment]
Yet another approach would be to add a callback parameter to [Skip](https://phpbench.readthedocs.io/en/latest/writing-benchmarks.html#skipping-subjects):

```php

/**
 * @Skip(callback="isBenchmarkIsApplicable")
 */
public function benchHash(array $params)
{
}
```

**Comment by rybakit** [comment]
> SkippedBenchmarkException could be thrown from the benchFoo method.

I'm not sure why it could be thrown from `benchFoo`. My idea was to throw this exception only in the `validate*` methods.

**Comment by dantleech** [comment]
Yeah, you could throw from the `Before` / `Validate` methods, but it would also be convenient to throw control from the benchmark method itself (not all benchmarks care about that overhead).
