### ISSUE TITLE
--tolerate-failure missing for xdebug:profile and --assert not working

### ISSUE THREAD

**Issue by kleijnweb** [phpbench/phpbench#561]
When using the Assert annotation, `xdebug:profile` become unusable. Ideally one would just be able to use `--tolerate-failure`.

**Comment by dantleech** [comment]
yeah, makes no sense actually to enable assertions for profiling. Would be happy to disable them unconditionally when running that command.

**Comment by kleijnweb** [comment]
That also sounds fine :)

**Comment by dantleech** [comment]
It would make sense to have Assertions on the `xdebug:trace` command however so that you could assert on number of calls etc. So maybe some more thought required, but yeah, `--tolerate-failure` would probably be a good place to start.

**Comment by dantleech** [comment]
Assertions have been re-implemented Running them with `xdebug:profile` can cause "failures", but they don't affect the profile generation. Closing.
