### ISSUE TITLE
Built-in benchmarks included?

### ISSUE THREAD

**Issue by 4n70w4** [phpbench/phpbench#587]
Hi! Does this package have built-in benchmarks?
I just need to run on 2 servers and see which one is better.

If there are built-in tests - tell me how to run.
If not, then this is a request for their creation =)

**Comment by dantleech** [comment]
There is no option to run tests (e.g. file read/write, maths, etc etc) independenty of a test file if that's what you mean.

**Comment by dantleech** [comment]
Well, it's up to you. Those benchmarks are not trying to prove anything specific regarding server performance.

PHPBench also makes some micro benchmarks to compare environments which you get with the env report:

```

**Comment by 4n70w4** [comment]
@dantleech thx. Then this is a request for creating these tests =)

**Comment by dantleech** [comment]
Closing as this is a use case for PHPBench, and not something I want to maintain in the core.
