### ISSUE TITLE
phar file is missing since the last release

### ISSUE THREAD

**Issue by jakzal** [phpbench/phpbench#597]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/190447/53698649-a2329e00-3dd7-11e9-80be-032ecfb84bd4.png">

**Comment by dantleech** [comment]
:man_facepalming: maybe time to switch to GH releases.

**Comment by dantleech** [comment]
Should be fixed as of https://github.com/phpbench/phpbench/commit/77ea0f102fa140cd56dae0b1e644f5e972988245
