### ISSUE TITLE
Benchmark without class

### ISSUE THREAD

**Issue by flip111** [phpbench/phpbench#598]
I started reading the docs https://phpbench.readthedocs.io/en/latest/quick-start.html#create-your-project

I see i need to create a separate class and file for a benchmark. But i would rather put some benchmarks and some functions to test together in one script. An interface similar to https://github.com/devster/ubench would be nice. Why not just use ubench then, you might ask? Phpbench seems to provide a lot of very nice features and also is more up to date.

Is there any way to use this package in a more simpler way?

**Comment by dantleech** [comment]
Being able to create such scripts won't happen in this major version of PhpBench (I was thinking about having a programatic interface in a "version 2" e.g. [like this](https://github.com/phpbench/pipeline), but that requires more thought).

But it's already easy (maybe even easier?) to create benchmarks with a class:

```
class MyBench
{
    public function benchFoo()
    {
        sleep(1); // etc
    }
}
```

You can then just do `phpbench run MyBench.php`

**Comment by flip111** [comment]
Perhaps it's possible to provide a function that accepts a [callable](https://secure.php.net/manual/en/language.types.callable.php) constructs an anonymous class on the fly and benchmarks this class?

**Comment by dantleech** [comment]
Not really, PhpBench depends on instantiating your benchmarking class, and has lots of associated functionality dependent on the class and it's metadata (e.g. annotations). That's just fundamental to the way it works at the moment.

I would personally like to see a more flexible library behind PHPBench as indicated above. But for now, I don't see this happening soon.

**Comment by flip111** [comment]
It's possible with use of reflection and php source code parsing to discover the function under test and copy it to a temporary file. This might be an option for a later major version.

**Comment by dantleech** [comment]
Closing for now.
