### ISSUE TITLE
Documentation is slightly wrong considering the DBAL configuration

### ISSUE THREAD

**Issue by Christoph-Harms** [phpbench/phpbench#601]
The docs give an example on how to configure DBAL for phpbench. The `extensions` array in the config file is not an array but an object in the given example, which is wrong JSON syntax.

Also, just to make clear where to put these configs, it would be nice to add the info that this has to be put into the `phpbench.json`. Which might seem obvious, but just to be extra clear, I think it would be nice. Also, other examples in the docs do have this info.

**Comment by dantleech** [comment]
Thanks, to be honest I would like to deprecate this extension (or at least put it in a separate repository). It doesn't map 100% with all of PHPUnits functionality (I think it can only record a small set of metrics IIRC).

But interested to hear any feedback you have on it, or how you are using it.

**Comment by flobee** [comment]
> Thanks, to be honest I would like to deprecate this extension (or at least put it in a separate repository). It doesn't map 100% with all of PHPBench's functionality (I think it can only record a small set of metrics IIRC).
> 
> But interested to hear any feedback you have on it, or how you are using it.

I'm playing aroud with it (dbal driver) an i find out: it doesnt store all records like you see when using --output=console yust one of it (maybe the "best" goes to the db).

Now im thinking creating a shell script which stores the xml files in centralized store (eg. a DB) to collect results from different cpu's with or without rendering the xml....

Why do you want to split it or mark it as deprecated?

**Comment by dantleech** [comment]
Maintainence -it doesn't map 100% as you found out, and it would be better if PhpBench left more to the user here. (It could still live as an extension)

On 22 January 2020 15:36:55 CET, flobee <notifications@github.com> wrote:
>> Thanks, to be honest I would like to deprecate this extension (or at
>least put it in a separate repository). It doesn't map 100% with all of
>PHPBench's functionality (I think it can only record a small set of
>metrics IIRC).
>> 
>> But interested to hear any feedback you have on it, or how you are
>using it.
>
>I'm playing aroud with it (dbal driver) an i find out: it doesnt store
>all records like you see when using --output=console yust one of it
>(maybe the "best" goes to the db).
>
>Now im thinking creating a shell script which stores the xml files in
>centralized store (eg. a DB) to collect results from different cpu's
>with or without rendering the xml....
>
>Why do you want to split it or mark it as deprecated?
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/phpbench/phpbench/issues/601#issuecomment-577210261

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by flobee** [comment]
if the xml generation still exists (which i put to the db) go ahead :-)
