### ISSUE TITLE
Combine file location with phpunit locations? General docs

### ISSUE THREAD

**Issue by flobee** [phpbench/phpbench#603]
Hi. It can make sense having a structure like this (base on phpunit) to add phpbench in complex structure:

```
tests/src/module/a/controller/AControllerTest.php
tests/src/module/a/controller/BControllerTest.php
tests/src/module/a/controller/CControllerTest.php

to:
tests/src/module/a/controller/AControllerBench.php
tests/src/module/a/controller/AControllerTest.php
tests/src/module/a/controller/BControllerBench.php
tests/src/module/a/controller/BControllerTest.php
tests/src/module/a/controller/CControllerBench.php
tests/src/module/a/controller/CControllerTest.php
```
phpunit is listening by default for *.Test.php files.

I havent found an option for phpbench like:
```
https://phpunit.readthedocs.io/en/8.3/textui.html
--test-suffix ...           Only search for test in files with specified
                              suffix(es). Default: Test.php,.phpt
```

The other thing: Can you show some complex setups e.g in the documentation? 
Like you see. I want to benchmark application calls. 
Setups for this are more difficult because some things needs to be mocked or hacked. 
The docs are difficult to understand about the messurement. Too many options :-) 
When does it start collecting timings when not (eg: Class Before*,After or method Subject anotations) . phpunit has a clean structure. e.g. setup() and tearDown() where i can do the initial stuff to test the things right after. But for benchmarks this seems very open with the annotations for phpbench and a kind confusing for me.
Thx for help/ informations! Kind regards Florian

**Comment by dantleech** [comment]
In general I use:

```
src/Domain/MyClass.php
tests/Benchmark/Domain/MyClass.php
tests/Unit/Domain/MyClass.php
```

**Comment by flobee** [comment]
> In general I use:
> 
> ```
> src/Domain/MyClass.php
> tests/Benchmark/Domain/MyClass.php
> tests/Unit/Domain/MyClass.php
> ```

What i do .. since then :-)
