### ISSUE TITLE
Blinken progress output breaks on narrow terminals

### ISSUE THREAD

**Issue by rask** [phpbench/phpbench#606]
Given I have a benchmark with iteration count that exceeds 12 or so (e.g. it will output iterations on multiple rows), and when I have retry threshold in use, and when I have ops/ms in use and the ops exceed 9999 (i.e. become 5 or more characters wide), blinken will break and start creating new output lines instead of adjusting the old already printed lines.

When I use the same values on a wider terminal, the issue goes away. When the ops/ms is maximally 9999 the issue goes away.

My terminal is on Linux Ubuntu, and I use tmux to split panes. My screen is a 1920x1080 and the issue exists in 50% wide panes and smaller.

**Comment by dantleech** [comment]
Yes, this will happen currently. We need to take into account the number of cols (which could now be inferred from the Symfony `Terminal` class).

**Comment by rask** [comment]
The problem I see with inferring at runtime is that how do we know that the benchmark result (e.g. ops/s) is 3, 4, 5, or even more characters wide so the results can be split to the correct amount of rows? Or is it possible to reflush the whole blinken table in case one of the values reaches the threshold?

**Comment by dantleech** [comment]
Ideally the progress logger(s) would resize dynamically, and the whole rendering process could be abstracted, not sure if there would be an easier way, it's all quite "dumb" currently.

**Comment by rask** [comment]
I see. I'm not super versed in the console world but I can try and see if I can spot any good libraries for console thingies.
