### ISSUE TITLE
How to bootstrap entire application, instead of benchmark suites/methods?

### ISSUE THREAD

**Issue by rask** [phpbench/phpbench#607]
Right now when the `bootstrap` configuration is used, it will be included every time a benchmark suite class is run (a bit like `@BeforeMethods`). My brain is telling me that `bootstrap` should be included just once when the application loads, and `@BeforeMethods` should be for usage when bootstrapping things inside the benchmark suite.

I presume this thing is happening because of the templated forking runner system.

What approach should I take if I want to have a bootstrap that is run once per application, not once per class/method run?

The main issue is that I want to run functional benchmarks, and bootstrapping includes creating a database for the suite. Right now I am tearing down and recreating an entire database with fixtures before each method call, which takes more time than the benchmark itself should take.

**Comment by rask** [comment]
Right now I'm bypassing this using a wrapping script that runs the database bootstrapping:

```php
#!/usr/bin/env php
<?php declare(strict_types = 1);

require_once(__DIR__ . '/vendor/autoload.php');

// Args without the binary in place.
$args = array_slice($_SERVER['argv'], 1);

// This call inits dbs and other stuff that does not rely on the phpbench process execution itself
bootstrap_for_benchmarks();

passthru(__DIR__ . '/phpbench ' . implode(' ', $args), $exit);

exit($exit);
```

This is not usable with the `php_wrapper` configuration as is, so will need to dig a little how it could work.

**Comment by dantleech** [comment]
There is `@BeforeClass` or similar which is probably the closest thing to do within Phpbench itself.

But if you are depending on heavy fixture loading, then it could make more sense to do that in a separate script which is called during CI, or on demand. As you are then able to quickly run the benchmarks without the overhead of reinitializing the system state.

In my experience doing this type of thing as part of the benchmark / test run itself just adds unrequired latency to the test feedback cycle.

**Comment by rask** [comment]
Oh there was a `@BeforeClass` as well. Need to see if the slowdown is tolerable when I use that. `@BeforeClassMethods` wa a no go obviously. If nothing else the script I pasted seems to work well for my use-case for now.

**Comment by dantleech** [comment]
Assume this is all good :+1:

**Comment by rask** [comment]
Yeah I'll open a new issue if I run into trouble, for now the setup works well enough.
