### ISSUE TITLE
Running on GitHub actions

### ISSUE THREAD

**Issue by tillkruss** [phpbench/phpbench#608]
Does anyone have experiences running benchmarks on GitHub's Actions?

I'm not sure if they would provide accurate results since I assume they are shared environments?

**Comment by dantleech** [comment]
I haven't tried. Would be interesting to find out.

**Comment by rask** [comment]
I would say that with the shared/public runners you'll get shaky data. Maybe useful for informational purposes, but unstable in terms of verifiable benchmarks. Maybe with a dedicated private runner you could get numbers that are of use when comparing builds, assuming you configure the build server for stability in resource availability.

**Comment by tillkruss** [comment]
@rask that's what I was thinking.

**Comment by dantleech** [comment]
I am running regression tests on GH actions https://github.com/phpactor/worse-reflection/runs/2252560864?check_suite_focus=true . The runners are indeed flakey, but I use a tolerance of 10% which is generally working, and can catch serious regressions.

**Comment by drupol** [comment]
Sorry to dig up such old topics, but I did something similar with Github actions, without using any shell script file.

Find it here: https://github.com/loophp/iterators/runs/4700362099
