### ISSUE TITLE
Add a configurable timeout per benchmark

### ISSUE THREAD

**Issue by rask** [phpbench/phpbench#613]
I'm missing a configurable value where I could set a timeout value after which a revolution or iteration is deemed as failed, and is skipped _instantly_.

`@Assert` exists, but that only runs after a benchmark method has run its course.

Could there be a `@Timeout` that skips benchmarks where either a revolution or an iteration takes too long?

**Comment by dantleech** [comment]
At the iteration level at least we could set the process timeout. I don't think we want to do this at the rev level, as it would affect the benchmarking times (needing to check if the timeout is exceeded)

**Comment by rask** [comment]
Fail would be better, yes. With skipping I meant that if a timeout occurs (perhaps with a few retries) it marks it as failed and skips the rest of the same benchmark method.

Iteration level sounds good for me, as that will catch revolution level at the same time.

Do you think adding an insta-failure event to the process is simple or more complex? As in is there any infrastructure to bail out in place already or would that be new code just for this feature? Or would parts of the error state bailing code work for this as well? IIRC errors make the tests end as soon as some error happen?
