### ISSUE TITLE
Unable to use DateTime value in provider

### ISSUE THREAD

**Issue by othercorey** [phpbench/phpbench#615]
If I use a `DateTime` instance in a provider, phpbench errors with:

>In Reflector.php line 109:
>Overloaded object of type DateTime is not compatible with RecursiveArrayIterator

```
    public function provideTypes()
    {
        yield 'first' => ['time' => new DateTime()];
    }
```

**Comment by othercorey** [comment]
This code seems to recursively walk the provider set, but I am not sure I understand why.  The value are just passed as an array to the benchmark method, right?

```
        // validate parameters
        $parameters = new \RecursiveIteratorIterator(new \RecursiveArrayIterator($parameterSets));
        iterator_apply($parameters, function (\Iterator $iterator) {
            $parameter = $iterator->current();

            if (!is_scalar($parameter) && isset($parameter)) {
                throw new \InvalidArgumentException(sprintf(
                    'Parameter values must be scalar. Got "%s"',
                    is_object($parameter) ? get_class($parameter) : gettype($parameter)
                ));
            }
        }, [$parameters]);
```

**Comment by dantleech** [comment]
> The value are just passed as an array to the benchmark method, right?

Yes, I think the reason was to validate to ensure that no objects were present, only scalars are supported (that excludes DateTime) due to the way the parameters are passed to the benchmarking script.

I think, however, that we could just use PHP serialization here and support all serializable objects.

**Comment by othercorey** [comment]
I suppose, if nothing else, the php error should be turned into a proper phpbench error.
