### ISSUE TITLE
dbal driver with --store can be only used if db:environment.value is a TEXT field

### ISSUE THREAD

**Issue by flobee** [phpbench/phpbench#620]
Hi

When using the dbal driver the --store option end in an error:
    SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'value' at row 9 

My value i this case ... ` | php | extensions | value :
```
Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, intl, json, exif, mysqli, odbc, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, phalcon, Phar, posix, readline, recode, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ds, Zend OPcache, xdebug
```
Fixed localy:
ALTER TABLE `environment` CHANGE `value` `value` TEXT NOT NULL;

Kind regards
Florian

**Comment by dantleech** [comment]
Thanks - looks like we need to change it here: https://github.com/phpbench/phpbench/blob/master/extensions/dbal/lib/Storage/Driver/Dbal/Schema.php#L115

**Comment by dantleech** [comment]
A pull request would be ideal, it should only be exchanging one type with another in the schema otherwise I wouldn't expect to do it for some time.

**Comment by flobee** [comment]
ok. 
is this a non public issue? can not find in the list?
I will change it. where to send the pull request? master?

**Comment by dantleech** [comment]
yeah `master` is the one - this is a public issue (#620)

**Comment by flobee** [comment]
Ok, hint: tests of master are failing (befor and after the change; other error).
Pull request (621)/ commit will mark this issue

**Comment by dantleech** [comment]
Tests seem fine though?
