### ISSUE TITLE
Environment variables through phpbench.json

### ISSUE THREAD

**Issue by fenric** [phpbench/phpbench#628]
```json
{
    "bootstrap": "vendor/autoload.php",
    "path": "src/Benchmark",
    "env": [
        {
            "name": "APP_ENV",
            "value": "test",
            "force": true
        },
        {
            "name": "SOME_VAR",
            "value": "foo bar"
        }
    ]
}
```

Are there any plans to implement something like this? This would help a lot when writing benchmarks when working with a database in a test environment...

What do you think about this?

**Comment by dantleech** [comment]
would something like

```
# .env
APP_ENV=test
SOME_VAR="foo bar"
```

```
soruce .env
phpbench run 
```

work?

**Comment by fenric** [comment]
```ini
APP_ENV=prod
```

I have the following configs:

`config/definitions/doctrine.php.prod`
`config/definitions/doctrine.php.test`

I want to run a benchmark in a test environment...

`phpunit` has the following:

```xml
<?xml version="1.0"?>
<phpunit>
    <php>
        <env name="APP_ENV" value="test" force="true"></env>
    </php>
</phpunit>
```

**Comment by fenric** [comment]
I understand that you can do this:

```bash
export APP_ENV=test && phpbench run
```

but I don’t know... it doesn't seem like a good practice...

**Comment by rybakit** [comment]
I used environment variables for [tarantool-php/benchmarks](https://github.com/tarantool-php/benchmarks), that consists of a bunch of `phpbench.json` files to benchmark different PHP extensions and their combinations on different versions of PHP (ZTS/NTS). To make it less painful to specify different settings for these configurations, I wrote a Makefile that hides the complexity.  However, this could have been made easier if phpbench had supported specifying custom settings through `phpbench.json` which would then be imported into the `PhpBench\Registry\Config` object. Something like:

*Async/phpbench.json.dist*
```json
...
"php_config": {
  "zend_extension": ["opcache.so"],
  "extension": ["async.so", "msgpack.so", "tarantool.so"],
  "opcache.enable_cli": 1,
  "pcre.jit": 1,
  "async.tcp": 1
},
"config": {
    "coroutines": 25,
    "retry_threshold": 3
}
...
```

*Parallel/phpbench.json.dist:*
```json
...
"php_config": {
  "zend_extension": ["opcache.so"],  
  "extension": ["parallel.so", "msgpack.so", "tarantool.so"],
  "opcache.enable_cli": 1,
  "pcre.jit": 1
},
"config": {
    "threads": 10,
    "retry_threshold": 3
}
...
```

**Comment by fenric** [comment]
@rybakit wow! tarantool client! how nice that I met you!

**Comment by dantleech** [comment]
> if phpbench had supported specifying custom settings through phpbench.json

how would you access those settings? reading this again today, specifying env vars could make sense (they can be passed to the child process)

**Comment by fenric** [comment]
> > if phpbench had supported specifying custom settings through phpbench.json
> 
> how would you access those settings? reading this again today, specifying env vars could make sense (they can be passed to the child process)

hello! I don't know... maybe so:

```json
{
    "environment": {
        "name": "test",
        "force": true
    },
    "bootstrap": "config/bootstrap.php",
    "path": "resources/benchmarks",
}
```

`bootstrap.php` – it contains the following:

```php
(new Dotenv)->usePutenv()->load(__DIR__ . '/../.env');
```

`.env` – it contains the following:

```ini
# dev or prod
APP_ENV="dev"
```

but, if we don't have another machine for tests, then we can't set the `APP_ENV` to `test`...

why do we need to set env for the app? as a rule, for the test environment we have other configs, for example:

`doctrine.php.test` – it contains the following:

```php
    'doctrine.configuration.master.connection' => [
        'url' => string('sqlite:///{app.root}/var/tmp/app.sqlite'),
    ],
    'doctrine.configuration.slave.connection' => [
        'url' => string('sqlite:///{app.root}/var/tmp/app.sqlite'),
    ],
```

**Comment by dantleech** [comment]
yes, ok, I think that makes sense - but was more wondering about @rybakit 's comment, as he implied not using env vars.
