### ISSUE TITLE
Realistic benchmarks of rendering websites in popular frameworks? (e.g. in repos using phpbench)

### ISSUE THREAD

**Issue by TysonAndre** [phpbench/phpbench#630]
Sorry if this is off-topic. The slack link in README.md is expired, and I didn't see this in the FAQ on the website or other GitHub issues similar to this.

Looking at https://github.com/phpbench/phpbench/network/dependents?package_id=UGFja2FnZS01NDIzNTAwNzY%3D in https://github.com/laminas/laminas-stdlib , I see it uses it, and will try that, but I was wondering about applications using phpbench for other frameworks. (for websites, Symfony, commonly used programs, etc)

Context: When proposing/reviewing a change to php-src such as `https://github.com/php/php-src/pull/4783`, it would be useful to know if it would increase or decrease the amount of time typical macro use cases would take.

Also, google searches for php benchmarking show results such as https://www.phoronix.com/scan.php?page=article&item=php-74-benchmarks&num=2 (the graph mention it uses phpbench), but I'm guessing it's running the sample/math benchmarks (I'm not certain which tests it's running or how they're weighted from the graph).

- Having a recommendation (e.g. in the FAQ) for "PHPbench (web frameworks)" may give people creating/reading those blogs a better idea of what to expect from php upgrades.

**Comment by dantleech** [comment]
Hi, no I'm not aware of any "website" benchmarks using PHPBench (assume you mean "internal" macro benchmarks as opposed to HTTP?). It would be nice to collect a list.

I know the [Zend Service Manager](https://github.com/zendframework/zend-servicemanager/blob/master/phpbench.json) uses it, might also be worth scanning the [dependents](https://packagist.org/packages/phpbench/phpbench/dependents?order_by=downloads) on packagist.

Sorry I can't be of more help - not really sure what the question is here. the Slack link should be for the Symfony slack.

> Also, google searches for php benchmarking show results 

This is just a name conflict I think, as far as I know they are not using this package.

**Comment by TysonAndre** [comment]
> Hi, no I'm not aware of any "website" benchmarks using PHPBench (assume you mean "internal" macro benchmarks as opposed to HTTP?). It would be nice to collect a list.

Yes, I meant internal benchmarks with no http server (e.g. along the lines of repeatedly render index.html, blog posts, etc from file configs or APCu data, with opcache enabled). If it was easy to set up, http server tests not involving phpbench might also be useful.

> the Slack link should be for the Symfony slack.

I'm referring to `Join the #phpbench channel on the Slack Symfony Devs channel.
`, which links to https://symfony-devs.slack.com/join/shared_invite/enQtMzM3NDA1NzEyMzg0LTgyNGYwYjFjMjY5YjllYWZkYTY2OWM4MDQzZTgzMmNjNGI3ZDJhYzE2Yjc4NmFmM2JiOTZjODg2MGJlM2RjMDU , which renders a page saying the following

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

----

> This is just a name conflict I think, as far as I know they are not using this package.

That sounds plausible.
