### ISSUE TITLE
Blackfire extension

### ISSUE THREAD

**Issue by jaapio** [phpbench/phpbench#631]
Hi,

First of all thanks for this amazing tool. It helped me already a lot of times to find out what was slowing down my applications and algorithms. 

This week I started a new extension to connect phpbench with blackfire, which I started to use recently. I wanted to benchmark my libraries and see the results in blackfire. 
I wrote an extension that provides a new executor and a logger. The logger will start a build in blackfire, and start a scenario on each iteration, and closes it again on finish. 
The executor is responsible to start the actual profiling. 

Using the logger feels kind of hackish, but I didn't found another way to hook into the start of a suite and variant, is there some event system available that could help me doing the same thing without having to misuse the logger? 

The executor is basically a copy of the template executor with a custom template. I needed to copy this because I had to pass some extra information to the template. If there is a better way to do this I would like to get some feedback :-)
It would be very nice if we could change the `TemplateExecutor` a bit so the variables passed to the template are configurable from the code, that would help me get rid of the copied code, because that was basically everything I needed to do. 

You can find the extension here: https://github.com/jaapio/phpbench-blackfire

Please let me know if there is anything I can do to help you improve this very useful tool.

**Comment by dantleech** [comment]
Hey, glad it's useful.

> t would be very nice if we could change the TemplateExecutor a bit so the variables passed to the template are configurable from the code

It could certainly be better - do you have an example of what you mean with `configurable from the code` ?

**Comment by jaapio** [comment]
It was easier to create a PR rather then trying to explain what I needed. 
https://github.com/phpbench/phpbench/pull/632

What do you think? Do you see any other ways to accomplish this? The new method `createTokens` can be overwritten by classes extending the templateExecutor, to make it possible to add extra variables that are needed to instruct blackfire in this case.

**Comment by dantleech** [comment]
I'd rather remove the abstract class completely - but that would be a much bigger task. I that change looks good :)

**Comment by rybakit** [comment]
Be careful when testing performance with Blackfire: https://www.reddit.com/r/PHP/comments/m1hqpb/dont_blindly_trust_profilers/.
