### ISSUE TITLE
Automatic revolutions

### ISSUE THREAD

**Issue by AndreKR** [phpbench/phpbench#635]
Often the question "how long should this benchmark run" is much easier to answer than "how many revolution should it do". So what for example Go's benchmark runner does is:
1. Determine the time the benchmark should run. Go's benchmark runner defaults to 1 second.
2. Run one revolution, measure the duration.
3. Predict how many revolutions are needed to run at least the specified duration.
4. Run that many revolutions.
5. Check if the specified duration has been reached, otherwise make a new prediction and start over from step 3.

**Comment by dantleech** [comment]
What is the advantage over revolving infinitely and stopping the benchmark after x amount of time?

**Comment by AndreKR** [comment]
Hm, I didn't really consider that as it wouldn't work together with #636. I'm also guessing that finding out the elapsed time is a rather expensive system call?

**Comment by dantleech** [comment]
Yep good point that makes sense.

**Comment by dantleech** [comment]
Closing now, I would like to provide more options in this regard though.

**Comment by dantleech** [comment]
Also related #224
