### ISSUE TITLE
Delegate the revolving to the benchmark function

### ISSUE THREAD

**Issue by AndreKR** [phpbench/phpbench#636]
An interesting feature of Go's benchmark runner is that it delegates the revolving to the benchmark function. This makes it really easy to have per-subject setup code and takes the function call overhead out of the picture. [This](https://phpbench.readthedocs.io/en/latest/quick-start.html#creating-and-running-a-benchmark) example would look like this:
```php
<?php

use Acme\TimeConsumer;

class TimeConsumerBench
{
    public function benchConsume(Benchmark b)
    {
       $consumer = new TimeConsumer();
       for ($r = 0 ; $r < b.Revolutions() ; $r++)
       {
          $consumer->consume();
       }
    }
}
```

**Comment by dantleech** [comment]
Yes - I considered the similar [here](https://github.com/phpbench/phpbench/issues/220). Although I think it would be more like extracting the benchmark code, and adding the instrumentation, to a function call in the template script rather than a class.
