### ISSUE TITLE
Feature: Improve debugging in benchmarking script

### ISSUE THREAD

**Issue by Danack** [phpbench/phpbench#640]
It seems that running phpbench against PHP master in an attempt to measure the jit performance gives an error.

```
# php bin/phpbench.php run --tag=with_jit --store

In Payload.php line 130:
                                                                                                                               
  Fatal error: Uncaught RuntimeException: Class has no method "providePoints" and it is not a callable in /tmp/PhpBenchq59OOq  
  :48                                                                                                                          
  Stack trace:                                                                                                                 
  #0 {main}                                                                                                                    
    thrown in /tmp/PhpBenchq59OOq on line 48   
```

Trying to investigate this is hard, as the stack trace from the process being run is unavailable.

What's the best way of investigating this issue.

**Comment by dantleech** [comment]
Hm, do you have this in a public repo? _Sounds_ like it can't find the data provider method on the benchmark class?

You could probably edit the `Payload.php` and prevent the temporary file from being deleted and run it manually.

**Comment by Danack** [comment]
That was actually just running it in the phpbench directory.

I've found the error and done a PR for that, but it is a bit annoying having to edit phpbench code to be able to debug issues like that.

so this is probably a feature request now, to make it easier.

**Comment by dantleech** [comment]
thanks, merged the PR. indeed an option here would be good.

**Comment by dantleech** [comment]
Added `remote_script_path` and `remote_script_remove` options: https://github.com/phpbench/phpbench/pull/670
