### ISSUE TITLE
How to ignore certain annotations?

### ISSUE THREAD

**Issue by shmax** [phpbench/phpbench#643]
Hi there, our code base uses some custom annotations that are specific to the phpstan library, for example:

```php
/**
 * @template T of Node
 * @phpstan-implements ArrayAccess<int|string, T>
 * @phpstan-implements IteratorAggregate<T>
 */
class NodeList implements ArrayAccess, IteratorAggregate, Countable
{

```

These seem to be giving phpbench fits. It complains with
```
 [Semantical Error] The annotation "@template" in benchmark: \GraphQL\Language\AST\NodeList was never imported. Did you maybe forget to add a "use" statement for this annotation? 
```

I've been poring over documentation and diving into code for an hour, and for the life of me I can't figure out how to configure phpbench with knowledge of these and other custom annotations.

And advice greatly appreciated!

**Comment by dantleech** [comment]
You can tell PHPBench not to use global imports with `"annotation_import_use" => false` in `phpbench.json`. You can then import the full FQNs of the PHPBench annotations, e.g. `use PhpBench\Benchmark\Metadata\Annotations\Sleep`

But I'd question why PHPBench is loading a`NodeList` class?

Typically I'd expect PHPBench files to live in a tests folder, e.g. `tests\Bench` and by default it only loads `*Bench.php` files?

**Comment by dantleech** [comment]
Ah, and I guess `annotation_import_use` won't help in case of these tags which, if anything, should be accounted for [here](https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Metadata/AnnotationReader.php) (maybe it could be made to be configurable).

**Comment by shmax** [comment]
Thanks much for the reply!

> "annotation_import_use" => false in phpbench.json

Is this really the _de facto_ way to do this? A search on github for that key only turns up 5 matches, and none of them are in json files.

> You can then import the full FQNs of the PHPBench annotations, e.g. use PhpBench\Benchmark\Metadata\Annotations\Sleep

That doesn't have meaning in the case of `@template`. There is no matching class by that name; it's just a custom annotation that the phpstan parser knows to watch for.

> But I'd question why PHPBench is loading aNodeList class?
I don't know, it's just one of the classes that is exercised in the code being benchmarked. Is phpbench not supposed to be parsing the phpdoc blocks of the files in the code it is testing?

> tags which, if anything, should be accounted for here
That's something else I don't understand. phpbench has Doctrine as one of its dependencies, and Doctrine defines an `AnnotationReader` class, which has a [addGlobalIgnoredName](https://github.com/doctrine/annotations/blob/e723cc77e1e05177e4900ead047ab20061e6d66e/lib/Doctrine/Common/Annotations/AnnotationReader.php#L54) method, which looks like exactly what we need. But phpbench seems to have copy/pasted an [older version of this class](https://github.com/phpbench/phpbench/blob/master/lib/Benchmark/Metadata/AnnotationReader.php). Unfortunately, it doesn't supply the same `addGlobalIgnoredName`.

I'm happy to open a PR, but phpbench seems like a fairly mature code base that has been around for a while, and it seems odd that I'm the first person to be in this situation, which makes me think we may be doing something fundamentally wrong...

**Comment by dantleech** [comment]
> Is this really the de facto way to do this?

Well, it's undocumented, I just remembered writing that functionality for some reason :)

> we may be doing something fundamentally wrong...

In general benchmarks would live in a separate folder, I tend to organize as:

```
src/
   Foobar.php
tests/
   Bench/
      FoobarBench.php
```

then you can run PHPBench `./vendor/bin/phpbench run tests/Bench` for example (or set the `path` in config)`

---

But feel free to make a PR if it helps illustrate your issue.

**Comment by shmax** [comment]
> In general benchmarks can live in a separate folder, I tend to organize as:

Yes, our benchmarks are in a dedicated folder, and the files are named with the "Bench" suffix. We refer to the benchmarks folder in our phpbench.json:

```json
{
  "bootstrap": "vendor/autoload.php",
  "path": "benchmarks",
  "retry_threshold": 5,
  "time_unit": "milliseconds"
}
```

But I just ran it with an explicit reference to the benchmarks folder, and I no longer get the complaints about unknown annotations, which is progress (why did it not read the `path` field from phpbench.json?)

Now, I get a new error: 

```
Notice: fgets(): read of 8192 bytes failed with errno=9 Bad file descriptor
```

I'll investigate more after work. Thank you for your help. 👍

**Comment by shmax** [comment]
Closing for now; I need to investigate why `path` wasn't used, and figure out the fgets thing, but those are different issues. Thanks again!
