### ISSUE TITLE
Anyway to set-up state before each iteration?

### ISSUE THREAD

**Issue by nkconnor** [phpbench/phpbench#644]
It's common practice to e.g. create an array of size N and then benchmark various (possibly mutable) ops on top of it. If there is no way to set-up state before each rev/iter/warm-up, then the array creation, or whatever set-up is required, has to be part of the benchmark (noise).

Is there a way to do set-up before each iteration?

**Comment by dantleech** [comment]
Sure you can use `@BeforeMethds({"setUp"})` for example: https://phpbench.readthedocs.io/en/latest/writing-benchmarks.html?highlight=BeforeMethods#subject-runtime-state-before-and-after

**Comment by nkconnor** [comment]
I thought this only ran before each subject and not rev/iteration?

**Comment by dantleech** [comment]
It's done before each _iteration_. (iterations are separate processes, revs are "inside the loop").

**Comment by nkconnor** [comment]
So you could use mutable state _if_ revs = 1. I'll try that!

**Comment by dantleech** [comment]
Bear in mind though - the accuracy of 1 rev is limited by the precision of the measurement (microseconds). I'd only recommend using revs=1 on slow benchmarks (measured f.e. in milliseconds)
