### ISSUE TITLE
[NFR] Numeric Literal Separator

### ISSUE THREAD

**Issue by Jeckerson** [phpbench/phpbench#662]
With 7.4 came new RFC: Numeric Literal Separator - https://wiki.php.net/rfc/numeric_literal_separator
Which gives possibility to write numeric values with separators and detect visually and more easily.

Example:
```
/**
 * @Revs(100_000)
 * @Iterations(5)
 */
```

```
/**
 * @Revs(1_000_000)
 * @Iterations(5)
 */
```

**Comment by dantleech** [comment]
There's no reason not to use commas here, e.g. `100,000`. Could support both...

**Comment by flobee** [comment]
does not belong to int "Unaffected PHP Functionality" https://wiki.php.net/rfc/numeric_literal_separator

**Comment by dantleech** [comment]
Yes - the Doctrine Annotations library would be responsible for this. With the alpha version of PHPBench you can use Attributes instead of annotations - and so this then becomes a non issue.
