### ISSUE TITLE
The "--uuid" option does not exist.

### ISSUE THREAD

**Issue by tomasnorre** [phpbench/phpbench#735]
Hi, 

When running the examples from the documentation 
```shell 
$ phpbench run tests/Benchmark/MyBenchmark.php --tag=original --retry-threshold=5 --iterations=10
$ phpbench run tests/Benchmark/MyBenchmark.php --report=aggregate --uuid=tag:original --retry-threshold=5 --iterations=10
``` 
I get the error `The "--uuid" option does not exist.` I know that you are planning to switch from --uuid to --ref, but until then I would need to stick to the old convention and that isn't working for me. 

Can it be that I do something wrong? My config is quite small (bare minimum). 

```json
{
    "bootstrap": "vendor/autoload.php"
}
```

Any hints in this would be appreciated. Thanks

**Comment by tomasnorre** [comment]
This is only a problem in 0.17.1 and not in dev-master, so will close this issue again.

**Comment by dantleech** [comment]
Yes, sorry it would be better if the docs defaulted to the stable branch
