### ISSUE TITLE
[NFR] Benchmark code coverage

### ISSUE THREAD

**Issue by Jeckerson** [phpbench/phpbench#736]
Is it even possible to implement feature like that?

Examples:
* PHPUnit - https://phpunit.readthedocs.io/en/9.3/code-coverage-analysis.html
* Codecov.io - https://about.codecov.io/product/features/

**Comment by dantleech** [comment]
Sure it's possible, not sure how useful it would be? Not all code is performance sensitive, and I guess we probably don't want to aim to cover all possible code execution paths with benchmarks.

**Comment by Jeckerson** [comment]
> Not all code is performance sensitive

That is true, but when you see the dynamic of % during the time and can visually see what parts of the code are covered - makes the process more optimized. Especially when periods, between benchmark writes, are long and you already forgot most of the process. :)

**Comment by dantleech** [comment]
I'm not sure this would be that useful -- would it be an aim to have 100% coverage? In my experience only a small % of code should be covered by benchmarks - does you experience differ? do you have an example?

But for now I'll close this, feel free to carry on the discussion, maybe we can re-open.

**Comment by Jeckerson** [comment]
[Phalcon framework](https://github.com/phalcon) team has a plan to cover whole code with benchmark to monitor performance degradation over time. The more we know about how much our code is covered, the more history we will have. And the more right decisions might be done, in terms of bug fixes and implementations of new features.

**Comment by dantleech** [comment]
Interesting - do you have a plan to store and analyse the benchmark data over time?

I'm still not sure about the coverage though - but I imagine it should be possible at least via. an extension: you can wrap the PHP executable or use a custom INI file and then process the data generated by XDebug for example (not actually sure how coverage works in practice).

**Comment by Jeckerson** [comment]
> Interesting - do you have a plan to store and analyse the benchmark data over time?

Yes.

You are right about extension, but all point of this NFR, is to see if possible to encapsulate inside single project.
