### ISSUE TITLE
composer deps for php8 ( php > 7.2)

### ISSUE THREAD

**Issue by flobee** [phpbench/phpbench#757]
Hey. Die festen bindungen an eine php version neven total weil 0.16 grundsätzlich auch unter php8 laufen kann.
"php": "^7.2", (composer.json) ist in diversen tags hinterlegt und composer will nur mit gewallt installieren :-(

also: php >= Version mit der es laufen muss oder  "php": "^7.2 || ^7.3 || ^8.0" funktioniert wunderbar wenn man composer mit phpbench/phpbench: "*" configuriert (auf user seite) und composer --prefer-source nutzt um dessen unterstützung der dependeny checks erfolgreich zu erhalten. ich brauch eine version die laufen kann, nicht die stricte reduktion nichts mehr nutzen zu können :-) 
LG aus HH

**Comment by dantleech** [comment]
Hey, my German isn't that great. I am preparing PHPBench 1.0 and the latest alpha tag will work under PHP 8.

**Comment by flobee** [comment]
yeah, i've seen that but "beta" is our min requirement. 
pls think to extend existing tags supporting older versions under php8 which works in lot of cases. 

an intressting example how to include several php version under the hood: 
https://github.com/tiamo/spss/blob/master/composer.json
https://github.com/tiamo/spss/blob/master/.travis.yml
redused php features, less strict but works. 

even squizlabs/php_codesniffer does it. and your tool is of that category :-) (big up!)

**Comment by dantleech** [comment]
Why is `beta` the min requirement? The 0.x tags are technically pre-alpha..

**Comment by flobee** [comment]
not yours :-) my composer.json (min stability) because otherwise i would get not working dependencies because composer dont want to install and i dont want to force some installs which may work in a local situation but not for others.

my only chance is to fork your repo, change 0.16* | up  to alow php8 and then it will fit and work with my implementation. your 1.0 tree gives work on my side and i dont have time to do it now :-)

**Comment by dantleech** [comment]
hmm, seems I have done the versioning schema wrong: you can require `1.0.0-alpha6` but you can't require `@alpha`

**Comment by flobee** [comment]
That was the problem: 
```
Problem 1
    - phpbench/dom is locked to version 0.2.0 and an update of this package was not requested.
    - phpbench/dom 0.2.0 requires php ^5.4|^7.0 -> your php version (8.0.2) does not satisfy that requirement.
  Problem 2
    - phpbench/phpbench is locked to version 0.16.10 and an update of this package was not requested.
    - phpbench/phpbench 0.16.10 requires php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.

```

composer.json:

```
"require-dev": {
        "phpunit/phpunit": "^9",
        "composer/composer": "^2",
        "squizlabs/php_codesniffer": "^3",
        "phing/phing": "^2",
        "phpstan/phpstan": "*",
        "phpbench/phpbench": "^0.16"
    },
```

`1.0.0-alpha6`dont work out of th box: 
`[ERROR] Invalid user configuration: The option "archiver" does not exist....` I need to read the changelog :( :-)

**Comment by dantleech** [comment]
Yes, some things have been removed to simplify.

**Comment by flobee** [comment]
I just think if you can offer phar files? in old times i remember this problem happens very often. Dont know now. phpDocumentor was always a prblem with dependencys. !?

**Comment by dantleech** [comment]
Not sure what you mean - what problems are there with dependencies? You can install alpha6 - and there is a [PHAR file](https://github.com/phpbench/phpbench/releases/tag/1.0.0-alpha6)

**Comment by flobee** [comment]
Ah! thanx for the phar hint!
I just removed the "archiver" at the config and i'm fine. its working at all :-) It also stores the xml. Good :-)

 But with an only quick check of the docs and then look at the xml: There is no version info about the used phpbench version... Just as hint: If that structure changes this info will be a must have. Seems to be the same, isnt it? but this was a rough check.

**Comment by dantleech** [comment]
There is `<phpbench xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="@git_tag@">` which would get replaced in the PHAR version at least - could probably change this to get populated from composer.
