### ISSUE TITLE
compare baseline across git branches

### ISSUE THREAD

**Issue by staabm** [phpbench/phpbench#764]
overall I want to built a github action which perf compares the master branch against the changes of a PR using the baseline feature described at https://phpbench.readthedocs.io/en/latest/regression-testing.html

I am running into a problem, that after changing the git branch the UUID "original" can no longer be found.

```
$ php phpbench run benchmarks --report=aggregate --ref=original --retry-threshold=5

In XmlDriver.php line 68:

  Cannot find run with UUID "original"
```

running this command without changing the branch beforehand works like expected.

I guess phpbench is somehow building a "storage-id" and this one changes when changing git branches.
therefore I cannot compare the baseline against a change from a different git branch.

**Comment by dantleech** [comment]
Are you using the latest _tagged_ alpha? Try `composer require phpbench/phpbench@1.0.0-alpha6 ` (or `dev-master` tbh - unforatunately I got the versioning wrong so `@alpha` doesn't work)

**Comment by dantleech** [comment]
ok, you're using `dev-master` I'll have a look.

**Comment by dantleech** [comment]
hm, i can't reproduce this:

![image](https://user-images.githubusercontent.com/530801/111150773-6a45c000-8586-11eb-9992-8d1e07e3b6ed.png)

**Comment by dantleech** [comment]
Could the problem rather be that the storage is not persisted across the containers?

I tried a similar approach with GH actions - this involved publishing an artifact with the storage results and then including that artifact in the comparison run.

I found that the different containers/actions can have significantly different performance profiles - and that finally it was easier to perform the initial baseline and subsequent comparison _in the same action.

But interested to see how you go on this -- this approach is much cleaner if it's stable.

**Comment by staabm** [comment]
thx for your input. it gave me some inspiration to reduce the github action a bit.

I simplified the action further and do everything in a single `run:` step.
the initial reported problem still persists though.

https://github.com/staabm/parsica/blob/106d437260ce21ffd943e52b94f90fe804ef203e/.github/workflows/benchmark.yml
https://github.com/parsica-php/parsica/pull/37/checks?check_run_id=2112672348

**Comment by dantleech** [comment]
I think this is the issue:

```
    "xml_storage_path": "/tmp/.phpbench/storage"
```

I don't think that's configured on master, so PHPBench then can't find the referenced baseline.

FWIW I would add `.phpbench` to gitignore.

**Comment by staabm** [comment]
after getting rid of the mentioned config it works. I can see the diff beeing generated.
