### ISSUE TITLE
phar release to support php8

### ISSUE THREAD

**Issue by mihai-stancu** [phpbench/phpbench#768]
Hello,

`phpbench.phar v0.17.1` was released 9mo ago.
`composer.require.php: ^7.1 || ^8.0` was updated 4mo ago.

Unfortunately this means that the current phar release doesn't work on PHP8.

Is there any possibility of releasing another phar build?

**Comment by dantleech** [comment]
yes -- i'm working on 1.0 but probably makes sense to back port the 8.0 support as with https://github.com/phpbench/phpbench/issues/757

**Comment by dantleech** [comment]
actually the alpha versions do have PHARs: https://github.com/phpbench/phpbench/releases/tag/1.0.0-alpha6 - but may not be as stable (e.g. alpha6 has some issues for sure)

**Comment by mihai-stancu** [comment]
@dantleech I was actually using `phive` to install `phpbench` packaged together with [jakzal/phpqa](https://github.com/jakzal/phpqa). 

`phive` is installing the most recent **signed** release by default (unless you specify you accept unsigned releases) so the release I had installed was `0.16.9` (last signed release).

pingback: jakzal/toolbox#369

**Comment by mihai-stancu** [comment]
@dbalabka could I possibly trouble you for a link to documentation of how to GPG sign a phar release?

A lot of maintainers have signed releases interspersed with unsigned releases -- I'm curious what the process entails, I'm assuming it's not 100% automatic due to security constraints so it's a burden on them.

**Comment by jakzal** [comment]
@mihai-stancu it depends how one builds the phar. With Box it's easy to sign afaik: https://github.com/box-project/box/blob/master/doc/configuration.md#signing-algorithm-algorithm 

Here's a blog post from one of Box maintainers: https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd

**Comment by dantleech** [comment]
The signature is automatically deployed with the release, but AFAIK Phive won't install non-stable versions.
