### ISSUE TITLE
phpbench indicator constant

### ISSUE THREAD

**Issue by staabm** [phpbench/phpbench#816]
like in phpstan, rector or similar tools it would be great there would be some kind of identifier which can be used to detect that code is run via phpbench

https://github.com/rectorphp/rector/blob/27f3544e8e8566f721a683055f54c8e703c649d9/bin/rector.php#L22
https://github.com/phpstan/phpstan-src/blob/c471c7b050e0929daf432288770de673b394a983/bin/phpstan#L16

see https://github.com/rectorphp/rector/issues/3330#issuecomment-625783407

**Comment by staabm** [comment]
I already tried adding a `define('__PHPBENCH_RUNNING__', true);` in several places, but it seems this is not propagated into the "runner" processes and therefore does not work like I need it

**Comment by dantleech** [comment]
yes, the SUT is unaware of PHPBench when `--executor=remote` is used (the default) - it runs in a new process. I'm not sure what the benefit of this feature is though?

**Comment by staabm** [comment]
our use case is, that we need some kind of whitelisting for some CLI tools, because autoloading in legacy apps which do not follow PSR rules is hard and we need to make sure that e.g. files which use top level `define` don't get loaded several times

**Comment by dantleech** [comment]
PHPBench will launch your app in a separate process with the bootstrap you provide, so you could f.e. `define('PHPBENCH_RUNNING')` in `phpbench_bootstrap.php` for example. But otherwise there is no autoloader contamination with PHPBench.

**Comment by dantleech** [comment]
Did you experience an issue with this? I don't think it should be an issue :thinking:

**Comment by staabm** [comment]
Yeah,.. my issue is the one described above.

**Comment by dantleech** [comment]
but what is the error?

**Comment by dantleech** [comment]
closing for now, sorry if i'm being dumb, but i can't see how this would be required.
