### ISSUE TITLE
Bug: Usage of composer InstalledVersions without proper dependency declaration

### ISSUE THREAD

**Issue by boesing** [phpbench/phpbench#821]
Hey there,

this package makes use of `Composer\InstalledVersions` but does not state that it requires composer v2.
You might want to require `composer-runtime-api` in v2 to ensure that `composer` v2 is used to install this package.

**Comment by dantleech** [comment]
Ah thanks. I assumed this was coming from ` package-versions-deprecated`, but it's available by default in composer 2 now. I created #822 to only show the package version if `InstalledPackages` class is existing.
