### ISSUE TITLE
Relative comparisons

### ISSUE THREAD

**Issue by tillkruss** [phpbench/phpbench#828]
It would be really useful to have relative comparisons between tests, similar to what phpbench.com is doing.

Maybe it defaults to a percentage `250%`, but could also be displayed as `2.5x`.

<img width="931" alt="Screen Shot 2021-05-09 at 11 07 27 AM" src="https://user-images.githubusercontent.com/665029/117582423-c9bbda00-b0b6-11eb-995d-dc8a8febf46f.png">

**Comment by dantleech** [comment]
One thought, we can allow the reporting engine to access the raw data table and compare against the lowest result:

```
   'comparison' => 'percent_diff(min(table["result_time_avg"]), mode(result_time_avg))',
```

Or, to be more specific we could add support for filtering data with a predicate:


```
   'comparison' => 'percent_diff(mode(table<variant_name === "benchMyImplementation">.result_time_avg), mode(result_time_avg))',
```

This would require some refactoring to implement a data table and extend the expression language.

Possibly there's another way.

**Comment by dantleech** [comment]
This is now possible as of https://github.com/phpbench/phpbench/pull/831
