### ISSUE TITLE
Modify throughput report

### ISSUE THREAD

**Issue by tillkruss** [phpbench/phpbench#830]
In the example below I'm fetching 2000 keys for each Iteration and I'd like to divide the `ops/sec` results by 2000 to get a more accurate number.

How can I use `@Format` and divide the `mode` column when using `throughput`?
```php
/**
 * @Revs(1)
 * @Iterations(10)
 * @Sleep(500000)
 * @OutputTimeUnit("seconds")
 * @OutputMode("throughput")
 * @Format("mode(variant.time.avg) as ms")
 * @ParamProviders("provideKeys")
 * @BeforeMethods("setUpCredis")
 * @Groups("credis")
 */
public function benchGetUsingCredis($params)
{
    foreach ($params['keys'] as $key) {
        $this->redis->get($key);
    }
}
```

**Comment by dantleech** [comment]
`@Format` is only for the progress output, in which case `(mode(variant.time.avg) / 1000) as ms`, you can also [override the report columns](https://phpbench.readthedocs.io/en/latest/report-generators/expression.html#columns) or add a custom report configuration.

**Comment by tillkruss** [comment]
Since this only applies to a single benchmark class, what approach do you recommend?

**Comment by dantleech** [comment]
this isn't possible at the moment, but `(mode(variant.time.avg) / count(variant_params["keys"])) as ms` might do it

**Comment by dantleech** [comment]
Assume this isn't an issue, re-open if you don't agree
