### ISSUE TITLE
Comments for KDE calculation

### ISSUE THREAD

**Issue by yourpropertyexpert** [phpbench/phpbench#900]
**This issue is purely about the comments. I have not found any problem with the actual code.**

In /lib/Math/Kde.php, the following things could do with tweaking:

Line 71: no docblock giving the type for "private $covariance;" (should probably be float)

Line 73: no docblock giving the type for "private $normFactor;" (should probably be float)

Line 91: The comments for the bandwidth selection mention references [3] and [4], but these references no longer appear in the comments. They should be (based on the Python library of which this is a fork)

```
.. [3] B.A. Turlach, "Bandwidth Selection in Kernel Density Estimation: A
           Review", CORE and Institut de Statistique, Vol. 19, pp. 1-33, 1993.
    .. [4] D.M. Bashtannyk and R.J. Hyndman, "Bandwidth selection for kernel
           conditional density estimation", Computational Statistics & Data
           Analysis, Vol. 36, pp. 279-298, 2001.
```

Line 200: The @param for the setBandwidth method should be either "scott", "silverman", or a float. That's to say, it should match the @param documented on line 111

If you want me to fork / PR, please just let me know... 

However, it's possible that the decision was taken to NOT type the returns on 71, and 73 because under some situations the PHP pow function can return an int rather than a float :-(

**Comment by dantleech** [comment]
Thanks, updated!
