### ISSUE TITLE
Lock up when running

### ISSUE THREAD

**Issue by Crell** [phpbench/phpbench#925]
I'm running the new 1.1.2 release on a PHP 8.1 docker container.  I have a single, very simple benchmark class with the following header:

```php
/**
 * @Revs(10)
 * @Iterations(3)
 * @Warmup(2)
 * @BeforeMethods({"setUp"})
 * @AfterMethods({"tearDown"})
 * @OutputTimeUnit("milliseconds", precision=3)
 */
```

When I run phpbench, however:

```
root@14803c7984b7:/usr/src/myapp# ./vendor/bin/phpbench run benchmarks/ -vvv
[DEBUG] Spawning process: '/usr/local/bin/php'  '/tmp/PhpBenchWSqTqO'
```

It just stops there and hangs, with no further output.  What am I screwing up here? :smile:

**Comment by dantleech** [comment]
you can isolate and debug it with [runner.remote_script_path](https://phpbench.readthedocs.io/en/latest/configuration.html#runner-remote-script-remove) set to `false` and [runner.script_path](https://phpbench.readthedocs.io/en/latest/configuration.html#runner-remote-script-path) set to f.e. `.phpbench/scripts`. You can then run the process indiated with `-vvv` and debug the script.

**Comment by Crell** [comment]
Hm.  Interestingly, the docs say `runner.script_path` exists, but the code rejects it as an invalid config option.  The closest key name I could find is `runner.remote_script_path`.  

Config:

```json
{
    "runner.path": "benchmarks",
    "$schema":"./vendor/phpbench/phpbench/phpbench.schema.json",
    "runner.bootstrap": "vendor/autoload.php",
    "runner.remote_script_remove": false,
    "runner.remote_script_path": "benchscripts"
}
```

Commands:

```
root@14803c7984b7:/usr/src/myapp# vendor/bin/phpbench run benchmarks/ -vvv
[DEBUG] Spawning process: '/usr/local/bin/php'  'benchscripts/php.template'
```

However, `benchscripts/php.template` does not exist when I quit the process.  Also, if I run `--executor=local` I get the same result, including the "spawning process" message.

**Comment by dantleech** [comment]
can you execute that script with PHP? does it hang? sounds like a docker issue maybe, if youve got it in a public repo I could have a look

**Comment by Crell** [comment]
See the `master` branch here: https://github.com/crell/serde

It needs a minimal .env file.  This should work:

```
COMPOSE_FILE=docker-compose.yml
HOST_IP=172.25.0.1
IDE_KEY=docker-xdebug
XDEBUG_PORT=9003
```

Then run `docker-compose run --rm php81 bash` for a shell.  Then run The commands I'm running above.  

Running `php benchscripts/php.template` works fine and gives me a serialized blob of the data in the script, as expected.

Thanks!

**Comment by dantleech** [comment]
If I run it I get:

```
PhpBench\Remote\Exception\ScriptErrorException Xdebug: [Step Debug] Could not connect to debugging client. Tried: 172.25.0.1:9003 (fallback through 
xdebug.client_host/xdebug.client_port) :-(
```

could it be it's waiting for the xdebug client?

**Comment by Crell** [comment]
Curious.  Xdebug works fine in this container; I've been running it all day.  Sounds like the IP address is perhaps different on your machine than mine.  (I hate Docker.)

Disabling Xdebug in the config file, however, does let it run to completion.  So... I guess it is an xdebug issue.  Of course, Xdebug should be off for benchmarks anyway so that's not exactly a loss. :smile: 

That takes care of my issue, I think.  Feel free to close this, unless you want to tweak the documentation per the notes above.  Thanks again!

**Comment by dantleech** [comment]
Maybe it's locking up because the sub-process tries to connect to the session which has already been opened by the parent process. Anyway, closing, might be worth adding an FAQ later though.
