### ISSUE TITLE
MemoryUnit allow IEC standards multipliers

### ISSUE THREAD

**Issue by popnikos** [phpbench/phpbench#927]
According to IEC and common usage, power of two should be also available in MemoryUnit multiplier

For instance : 
* 1024 bytes = 1 KiB (kibibyte)
* 1024 KiB = 1 MiB
* And so on

You can find information, and table showing prefixes, and multipliers on this wikipédia page :
[Unit of informations](https://en.m.wikipedia.org/wiki/Units_of_information)

**Comment by dantleech** [comment]
Please check https://github.com/phpbench/phpbench/pull/934
