### ISSUE TITLE
report.html_output_dir does not work

### ISSUE THREAD

**Issue by wikimatze** [phpbench/phpbench#929]
Hi Dan,

I'm playing around with your tool and love it so far. When I'm generation a HTML output via:

```
 ./vendor/bin/phpbench run tests/BenchMarks/MobileAppBannerBench.php --report=default --output=html
```

It generated the output in the default `.phpbench/html/index.html`.

But if I use the `report-html-output-dir`(see https://phpbench.readthedocs.io/en/latest/configuration.html#report-html-output-dir) and set it in my `phpbench.json`to:

```
{
    "$schema":"./vendor/phpbench/phpbench/phpbench.schema.json",
    "runner.bootstrap": "vendor/autoload.php",
    "report.html_output_dir": ".phpbench/test"
}
```

The output is still written to `.phpbench/html/index.html` - why not `.phpbench/test/index.html`instead?

Thanks for the great tool that I discovered only now.

**Comment by dantleech** [comment]
I've safely removed this option in https://github.com/phpbench/phpbench/pull/930/files
