### ISSUE TITLE
BUG: Mixed up labels in HTML output: bar_chart_time / benchmark

### ISSUE THREAD

**Issue by mhsdesign** [phpbench/phpbench#931]
Got following HTML output (pay Attention to the small labels like `bench_parser_old_big_ast`):

![image](https://user-images.githubusercontent.com/85400359/139585261-8c6d0161-75d7-4be4-a506-d449a46fe231.png)

Expected labels in the following order or as shown in the console:

bench_parser_old_big_ast
bench_parser_new_big_ast
bench_parser_old_medium_ast
bench_parser_new_medium_ast
bench_parser_old_small_ast
bench_parser_new_small_ast

![image](https://user-images.githubusercontent.com/85400359/139585290-2b624b81-1f11-4e29-a14e-4616e424e505.png)

The order of the test results is right but the labels seem to be mixed up in the HTML view.

**Comment by dantleech** [comment]
Thanks, fixed in #932

**Comment by dantleech** [comment]
and tagged 1.1.3

**Comment by mhsdesign** [comment]
wow that was fast thanks ;)
