### ISSUE TITLE
Outdated composer.json?

### ISSUE THREAD

**Issue by Dgame** [phpbench/phpbench#955]
[This PSR-4 entry](https://github.com/phpbench/phpbench/blob/master/composer.json#L84) is probably outdated since there is no `extensions/reports` folder. This causes a error while using phpstan:

>  Provided path "PhpBench\Extensions\Reports\" for prefix "vendor/composer/../phpbench/phpbench/extensions/reports/lib/" is not a directory

**Comment by dantleech** [comment]
oops yes, PR welcome :)

**Comment by Dgame** [comment]
> oops yes, PR welcome :)

Done

**Comment by Dgame** [comment]
@dantleech Could you provide a patch update? :)

**Comment by dantleech** [comment]
Done https://github.com/phpbench/phpbench/releases/tag/1.2.2
