### ISSUE TITLE
Configure @dependabot for automatic dependency upgrades

### ISSUE THREAD

**Issue by Ocramius** [phpbench/phpbench#961]
Today I came across the usual "which dependency is holding my upgrades back?" scenario :D 

In practice, I would suggest:

 * adding @dependabot core to this repository, to automate upgrades (perhaps weekly upgrades?)
 * adding auto-merge for dependabot upgrades
 * adding release automation, to allow for quick releases of improvements (I know you have your own tooling, so unsure if this is too much scope creep)

**Comment by dantleech** [comment]
Happy to add dependabot.

> adding release automation, to allow for quick releases of improvements

I don't have any tooling other than the Phar-build on tag. The overhead is basically updating the CHANGELOG which isn't too painful, in anycase would be happy to see the entire process automated.

> Today I came across the usual "which dependency is holding my upgrades back?"

What was the issue? How would dependabot save it?

**Comment by Ocramius** [comment]
> What was the issue? How would dependabot save it?

This week, it was just about allowing `psr/log:^3`

**Comment by dantleech** [comment]
hmm, I added dependeabot (initially with the `increase` strategy, now with `widen`) but it didn't update `psr/log`:

![image](https://user-images.githubusercontent.com/530801/147145950-db1d0013-9eaf-4ccf-98f1-4359e50aa800.png)

**Comment by Ocramius** [comment]
Possibly requires some other dependency bumps first? 🤔

**Comment by Ocramius** [comment]
(BTW, I really endorse "increase" as a strategy - widen is fine for popularity, but you want to run phpbench on PHP 8.1/latest anyway)

**Comment by dantleech** [comment]
yeah, I think I appreciate the argument (more stability, less maintainence, can use latest features). But I want to be able to use this on projects which are restrained (even through no fault of their own) to PHP 7.4 etc. At least that has been the policy so far.K

I've merged a PR to allow `psr/log` 2/3 https://github.com/phpbench/phpbench/pull/968

**Comment by dantleech** [comment]
and tagged 1.2.3

at some point I'll take inspiration from repos like BetterReflection and upgrade the release tooling, but for now it's "fine" :)

**Comment by Ocramius** [comment]
Awesome, thanks! 💪
