### ISSUE TITLE
PHP 8.1 - Deprecation due to implicit conversion from float on lib/Color/Gradient.php

### ISSUE THREAD

**Issue by agustingomes** [phpbench/phpbench#976]
Hello :)

I'm running some tests with PHP 8.1 and I see there's a deprecation popping up.

```sh
PHP Deprecated:  Implicit conversion from float 37.5 to int loses precision in /var/www/html/vendor/phpbench/phpbench/lib/Color/Gradient.php on line 82
```

The cause seems to be that a float is passed to this method:
https://github.com/phpbench/phpbench/blob/482856504a433bb44f3e0e335974e916a23f6188/lib/Color/Gradient.php#L82

Would it be a good solution to start accepting `float` in the method, instead of the current `int`? I can work on that change if that's a good way to go.

**Comment by dantleech** [comment]
yes I think so - might need to cast it to an int afterwards though

**Comment by agustingomes** [comment]
I've opened a PR for it: https://github.com/phpbench/phpbench/pull/977
