### ISSUE TITLE
Feature request: ability to import baseline/tagged benchmarks for runs

### ISSUE THREAD

**Issue by ricardoboss** [phpbench/phpbench#980]
Hi!

I want to be able to export a specific tag to store it in git so I can compare future revisions of the code against it.

One possibility I considered was storing the `storage.xml_storage_path` in git, but then my local runs would also be stored there and I would need to check if I accidentally added one to git every time. I find this too tedious and think there is a better way.

Another example of what I have in mind is the way [`psalm`](https://github.com/vimeo/psalm) handles baselines: you can provide a baseline file via command line or config and all errors it finds will be checked against it. I can also store the baseline file in git and it will be used by the CI to check if new errors where added by the changed code.

Any idea if this is possible and desirable for enough people?

**Comment by ricardoboss** [comment]
Apparently I have to learn to read docs thoroughly. "Storing Results" seems to be what I looked for: https://phpbench.readthedocs.io/en/latest/guides/benchmark-runner.html#storing-results

**Comment by ricardoboss** [comment]
I found this: https://phpbench.readthedocs.io/en/latest/guides/benchmark-runner.html#storing-results

But it appears it can only be used to generate reports afterwards. I would need to load it as a ref for a run.

**Comment by dantleech** [comment]
One thing to consider is that results will vary considerably based on the environment you are running the tests on. Two comuters will produce different results for sure, but also the environment may be effect by whatever programs you have running in the background at a particular point in time (for example).

Nailing down a reliable, long-term, performance profile is therefore pretty tricky (I believe) and I would always compare two branches at the same time.

**Comment by ricardoboss** [comment]
You're probably right. My interest lies in the relative difference a specific change has made to the overall benchmark. So I would generate my baseline via GitHub Actions runners once then use it to compare against future runs in GitHub Actions.

But this is aside from the actual request here. The feature would only need to provide a way to use a file as a ref or something like that.

**Comment by dantleech** [comment]
yeah, this would be particularly bad with GH actions: the load differs greatly between runners. @drupol has setup GH actions to benchmark and compare branches in the same run though: https://github.com/loophp/iterators/runs/4735870747

**Comment by drupol** [comment]
It's nice, but sometimes I get weird results. E.g.: The first benchmark is very fast while the second one is 10 times slower.

In the end, I came to the conclusion that using benchmarks on CI is a nice indicator, but it's not something to take for granted.

I always run the benchmarks locally anyway.

**Comment by ricardoboss** [comment]
If benchmarks run on cloud services differ as much as you describe, why even benchmark in the first place? The real application will probably run in a similar environment (i.e. virtualized/containerized) on similar hardware (cloud infrastructure).

So either I need more iterations per rev to get a more even distribution or I can ignore the benchmark anyway since the numbers won't tell me if something is actually as fast when run in a real world application.

What do you think?

**Comment by dantleech** [comment]
The aim of benchmarking is to increase the _relative_ performance of the code, i.e. all things being equal is this version of the code faster than that version?

**Comment by ricardoboss** [comment]
Exactly! Why would I need to guarantee that my local environment always has the same exact background processes running when I run benchmarks? Ideally, I would always have the same environment for every benchmark run. And IMHO a cloud service, like GitHub actions, is at least more consistent of an environment than my home PC.

**Comment by ricardoboss** [comment]
> Saying that, the storage system is in need of a rewrite [...]

What exactly needs to be done? Why a rewrite? Can anyone provide a ToDo list so someone can tackle this?

**Comment by dantleech** [comment]
> like GitHub actions, is at least more consistent of an environment than my home PC

not really! it can vary in extremes due to variable load. locally you have a better chance.

> What exactly needs to be done? 

nothing in particuar, I would just prefer it were done differently, but no particular objective reason.

---

relating to the original issue, it _is_ currently possible to do this.

```
$ phpbench run --dump-file=some_xml_file.xml
```

```
$ phpbench run --file=some_xml_file.xml
```
the above will use the results from the first as the baseline for the second.
