### ISSUE TITLE
Testing all benchmark groups at once?

### ISSUE THREAD

**Issue by aGiqs** [phpbench/phpbench#982]
Hi,

Thank you a lot for benchmark tool. I find it very useful :-)!

I created all my benchmark tests with group annotations
and used the following reporting settings in benchmark config:

```json
"reports": {
        "custom": {
            "extends": "aggregate",
            "sort": {"benchmark": "asc", "subject": "asc"}
        },
        "unittests": {
            "extends": "aggregate",
            "sort": {"benchmark": "asc", "subject": "asc"}
        }
    },
```

So if I want to generate a becnhmark report for one group, i run:

`$ phpbench run --group=my-group-name ./my-bechmark-tests`

Benchmark tool runs perfectly and I get my results.

Let's say now I want to create reports for all my benchmark tests but per group.

**Is it possible to configure benchmark reporting so,  that it detects all existing groups and tests one group after another?**

Thank you in advance for all kind of tips!

**Comment by dantleech** [comment]
yes... using report components you can aggregate and nest reports arbitrarily: https://phpbench.readthedocs.io/en/latest/report-components.html

**Comment by aGiqs** [comment]
Hi, thanx for your advice.  I discovered that I had an old version of phpbench.
I have upgraded it now and updated my config like this..
```json
 "report.generators": {
        "custom": {
            "extends": "expression",
            "cols": {
                "benchmark": null, // sort "asc" ?
                "subject": null,  // sort "asc" ?
                "set": null,
                "revs": null,
                "its": null,
                "mem_peak": null,
                "best": null,
                "mean": null,
                "mode": null,
                "worst": null,
                "stdev": null,
                "rstdev": null,
                "diff": "???" // "diff" as it was in former version?
            }
        },
...
```
There are some things that I am missing comparing to the old version and I haven't found how I could make it.

1. Could you advise me how I can sort my report results by benchmark and subject name (asc)?

2. It seems also, that 'diff' property doesn't exist anymore. I have found an example, how one can calculate percentage
`"percent_diff(mode(result_time_avg), mode(suite[subject_name = \"benchNothing\"][\"result_time_avg\"]))"`
But It's not the same value as it was in former 'diff'. So I can't compare my old results with the new ones.
Could you please tell me, how the old 'diff' was calculated? I mean, which properties you used for it..
If you could give me a formula, I'd be absolutely happy :-)

Then I tried also to create a config with components as you advised.. I guess I'm doing something wrong, as it doesn't work.
Here is my config:

```json
"report.generators": {
    "custom": {
        "generator": "component",
        "title": "My Aggregated Table",
        "components": [
            {
                "component": "table_aggregate",
                "title": "Table",
                "partition": "group_name",
                "groups":{
                    "group_name": {
                        "cols": ["group","benchmark", "subject", "mem_peak", "best", "mean", "mode", "worst", "rstdev" ]
                    }
                }
            }
        ]
    },
}
```
I tried to run it with:
`$ phpbench run  ./my-bechmark-tests/`

The report output was empty. No groups, no benchmarks, no subjects.. :-( 

Could you please help me with it?
I'm trying to create a config so that if I run `$ phpbench run  ./my-bechmark-tests/`, the report output would be something like this:

![example_report_ouput_for_all_groups](https://user-images.githubusercontent.com/99961596/156035088-5969b683-b6c8-4fac-9a26-f2f582a19ff5.png)

Thanx a lot in advance!

**Comment by dantleech** [comment]
You're correct, the diff and sorting is not currently supported with the "new" system :(

For your `component` report I think you're missing the `row` template: https://phpbench.readthedocs.io/en/latest/report-components/table-aggregate.html#example

```
                    "row": {
                        "benchmark": "first(partition['benchmark_name'])",
                        "net_time": "sum(partition['result_time_net'])"
                    }
```

**Comment by aGiqs** [comment]
I think I was wrong with the  report configuration with component. I tried several varients, but it seems to have a different functionality.
Now I've found almost the config that I need.
So there is a config to break reports by benchmarks.
```json
"report.generators": {
      "custom": {
          "extends": "expression",
          "break": ["benchmark"],
          "cols": {
              "benchmark": null,
              "subject": null,
              "set": null,
             ...
          }
      },
}
```
In this case all benchmark test reports are subdivided into benchmark classes.
I need exactly the same output but with the benchmark class annotation groups.
I've tried the following config, but it doesn't iterate the groups:
```json
"report.generators": {
      "custom": {
          "extends": "expression",
          "break": ["group"],
          "cols": {
              "groups": "subject_groups",
              "benchmark": null,
              "subject": null,
              "set": null,
               ...
          }
      },
}
```
Are there any possibility to break the reports by annotation groups this way?

**Comment by dantleech** [comment]
this won't work currently, but if I update the partioning (break) logic to interpret a list of `["group1", "group2"]` to `group1-group2` it works possibly as expected:

```
parser
+-------------+---------------+-------+
| benchmark   | subject       | mode  |
+-------------+---------------+-------+
| ParserBench | benchEvaluate | 381μs |
| ParserBench | benchEvaluate | 342μs |
+-------------+---------------+-------+

"console"
+-----------------+--------------+----------+
| benchmark       | subject      | mode     |
+-----------------+--------------+----------+
| RunCommandBench | benchDefault | 37.073ms |
| RunCommandBench | benchInBand  | 37.348ms |
| RunCommandBench | benchNoEnv   | 14.868ms |
+-----------------+--------------+----------+

(no group)
+------------------------------+--------------------------+----------+
| benchmark                    | subject                  | mode     |
+------------------------------+--------------------------+----------+
| AssertionProcessorBench      | benchAssert              | 1.204ms  |
| VariantSummaryFormatterBench | benchFormat              | 1.825ms  |
| HtmlRendererBench            | benchRender              | 6.348ms  |
| ComponentGeneratorBench      | benchGenerate            | 450μs    |
| ComponentGeneratorBench      | benchGenerate            | 452μs    |
| ComponentGeneratorBench      | benchGenerate            | 423μs    |
| ComponentGeneratorBench      | benchGenerate            | 2.125ms  |
| ComponentGeneratorBench      | benchGenerate            | 3.345ms  |
| ComponentGeneratorBench      | benchGenerate            | 5.121ms  |
| ComponentGeneratorBench      | benchGenerate            | 3.65ms   |
| ComponentGeneratorBench      | benchGenerate            | 5.336ms  |
| ComponentGeneratorBench      | benchGenerate            | 7.865ms  |
| ComponentGeneratorBench      | benchGenerate            | 5.167ms  |
| ComponentGeneratorBench      | benchGenerate            | 8.713ms  |
| ComponentGeneratorBench      | benchGenerate            | 10.746ms |
| ExpressionGeneratorBench     | benchGenerate            | 6.933ms  |
| DataFrameBench               | benchCreateFromRowArrays | 331μs    |
| DataFrameBench               | benchCreateFromRecords   | 953μs    |
+------------------------------+--------------------------+----------+

```

so can be a featre request

**Comment by dantleech** [comment]
assume this is surplanted by #983 feel free to continue discussion if not
