### ISSUE TITLE
Missing Attribute::IS_REPEATABLE for Assert Attribute class

### ISSUE THREAD

**Issue by nyamsprod** [phpbench/phpbench#997]
https://github.com/phpbench/phpbench/blob/facdd1259535ce70f76a5220ebe31476c96c4068/lib/Attributes/Assert.php#L7

I am getting the following error when using attributes

```
Attribute class PhpBench\Attributes\Assert is not repeatable but is already present above the method.
```

The code below produces the error
```php
    #[Bench\OutputTimeUnit('seconds')]
    #[Bench\Assert('mode(variant.mem.peak) < 2097152')]
    #[Bench\Assert('mode(variant.time.avg) < 10000000')]
    public function benchWithAttributes(): void
    {
        // internal bench code
    }
```

The same code using docblock works fine without error

```php
    /**
     * @OutputTimeUnit("seconds")]
     * @Assert("mode(variant.mem.peak) < 2097152")
     * @Assert("mode(variant.time.avg) < 10000000")
     */
    public function benchWithAnnotations(): void
    {
        //internal bench code
    }
```

**Comment by dantleech** [comment]
happy to accept a PR

**Comment by nyamsprod** [comment]
@dantleech PR submitted 

I am only testing that the repeatable issue is fixed and I assume the rest is correctly handled by the library.

Also as it was my first time using the library maybe other attributes may require the same fix but I did not check them. Maybe a future fix can be applied to them too.

**Comment by dantleech** [comment]
possibly it's required on others too, but for the meantime tagged 1.2.6 :)
